### ISSUE TITLE
TypeError: 'PDFObjRef' object is not iterable

### ISSUE THREAD

**Issue by corobin** [pdfminer/pdfminer.six#1004]
after updating to version 20240706 `extract_text()` on a pdf throws an error `TypeError: 'PDFObjRef' object is not iterable`

this did not occur on the previous version 20231228

```
Python 3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> from pdfminer.high_level import extract_text
>>> text = extract_text("Working.pdf")
>>> text = extract_text("Error.pdf")
Traceback (most recent call last):
  File "<pyshell#21>", line 1, in <module>
    text = extract_text(path)
  File "C:\Program Files\Python312\Lib\site-packages\pdfminer\high_level.py", line 169, in extract_text
    for page in PDFPage.get_pages(
  File "C:\Program Files\Python312\Lib\site-packages\pdfminer\pdfpage.py", line 171, in get_pages
    for (pageno, page) in enumerate(cls.create_pages(doc)):
  File "C:\Program Files\Python312\Lib\site-packages\pdfminer\pdfpage.py", line 127, in create_pages
    yield cls(document, objid, tree, next(page_labels))
  File "C:\Program Files\Python312\Lib\site-packages\pdfminer\pdfpage.py", line 63, in __init__
    mediabox_params: List[Any] = [
TypeError: 'PDFObjRef' object is not iterable
>>>
```

[Working.pdf](https://github.com/user-attachments/files/16152297/Working.pdf) - newly created blank page with acrobat

[Error.pdf](https://github.com/user-attachments/files/16152298/Error.pdf) - downloaded, I cannot change the process of its creation. I deleted all visible text on the page which did not appear to affect the behaviour of the error

**Comment by myhloli** [comment]
same error with this：https://github.com/opendatalab/MinerU/issues/198

**Comment by dhdaines** [comment]
Probably need to call `resolve1` on `self.attrs["MediaBox"]` as well... it's indirect objects all the way down...

**Comment by MarcoPellicciottaOSF** [comment]
> Probably need to call `resolve1` on `self.attrs["MediaBox"]` as well... it's indirect objects all the way down...

I had same error, using resolve1 fixed it for me.

**Comment by jroakes** [comment]
@MarcoPeli .  Y'all ok providing a bit more detail on the fix here, for users using:

```
from pdfminer.high_level import extract_text
text = extract_text("Working.pdf")
```

**Comment by CoE2013** [comment]
same error here with some PDFs - no solution so far.
Hint: version 20191125 can convert / handle PDF ...

**Comment by mimocha** [comment]
Same error here on Python 3.10.16, pdfminer version `20240706`, when running the example code with a PDF file version 1.4:

```python
from pdfminer.high_level import extract_text
text = extract_text("my_file.pdf")
print(text)
```

Downgrading to `pip install pdfminer.six==20231228` fixed the issue for me

**Comment by corobin** [comment]
this  has been fixed for quite some time but the latest release hasn't changed, could  a new release pushed so this gets fixed in production since it's a blocking issue that affects quite a few people?

**Comment by pietermarsman** [comment]
Can reproduce with the Error.pdf in the issue description:

```
PYTHONPATH=. python tools/pdf2txt.py ~/Downloads/Error.pdf
  File "/home/pieter/projects/pdfminer.six/tools/pdf2txt.py", line 323, in <module>
    sys.exit(main())
             ~~~~^^
  File "/home/pieter/projects/pdfminer.six/tools/pdf2txt.py", line 317, in main
    outfp = extract_text(**vars(parsed_args))
  File "/home/pieter/projects/pdfminer.six/tools/pdf2txt.py", line 65, in extract_text
    pdfminer.high_level.extract_text_to_fp(fp, **locals())
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/pieter/projects/pdfminer.six/pdfminer/high_level.py", line 133, in extract_text_to_fp
    for page in PDFPage.get_pages(
                ~~~~~~~~~~~~~~~~~^
        inf,
        ^^^^
    ...<3 lines>...
        caching=not disable_caching,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ):
    ^
  File "/home/pieter/projects/pdfminer.six/pdfminer/pdfpage.py", line 189, in get_pages
    for pageno, page in enumerate(cls.create_pages(doc)):
                        ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pieter/projects/pdfminer.six/pdfminer/pdfpage.py", line 146, in create_pages
    yield cls(document, objid, tree, next(page_labels))
          ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pieter/projects/pdfminer.six/pdfminer/pdfpage.py", line 71, in __init__
    resolve1(mediabox_param) for mediabox_param in self.attrs["MediaBox"]
                                                   ~~~~~~~~~~^^^^^^^^^^^^
TypeError: 'PDFObjRef' object is not iterable
```

**Comment by pietermarsman** [comment]
Note that I just released a new version that fixes this issue (by means of #1081), but will keep this open to also integrate the extra behavior in #1027.
