### ISSUE TITLE
A number of errors when installing on MACOS

### ISSUE THREAD

**Issue by poplarmedia** [pdfminer/pdfminer.six#107]
Hello,
I am getting a number of errors when installing on MACOS 10.11.6 with Python 2.7.10 installed. The install output from my terminal is below--any ideas? Is the permission issue in the last line the cause of everything else?

Thanks!
Matt

```commandline
$ pip install pdfminer.six
Collecting pdfminer.six
Requirement already satisfied: six in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from pdfminer.six)
Collecting pycryptodome (from pdfminer.six)
Installing collected packages: pycryptodome, pdfminer.six

Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/usr/local/lib/python2.7/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/Crypto'
```

**Comment by SMesser** [comment]
I get errors at the same stage (compilation of pycryptodome?), though my details are somewhat different:  The tail of the log is as follows:

```
    creating build/lib.macosx-10.13-intel-2.7/Crypto/SelfTest/Signature/test_vectors/PKCS1-PSS
    copying lib/Crypto/SelfTest/Signature/test_vectors/PKCS1-PSS/SigGenPSS_186-2.txt -> build/lib.macosx-10.13-intel-2.7/Crypto/SelfTest/Signature/test_vectors/PKCS1-PSS
    copying lib/Crypto/SelfTest/Signature/test_vectors/PKCS1-PSS/SigGenPSS_186-3.txt -> build/lib.macosx-10.13-intel-2.7/Crypto/SelfTest/Signature/test_vectors/PKCS1-PSS
    copying lib/Crypto/SelfTest/Signature/test_vectors/PKCS1-PSS/SigVerPSS_186-3.rsp -> build/lib.macosx-10.13-intel-2.7/Crypto/SelfTest/Signature/test_vectors/PKCS1-PSS
    running build_ext
    warning: no support for Intel AESNI instructions
    building 'Crypto.Hash._MD2' extension
    creating build/temp.macosx-10.13-intel-2.7
    creating build/temp.macosx-10.13-intel-2.7/src
    cc -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -arch i386 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -DLTC_NO_ASM -Isrc/ -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c src/MD2.c -o build/temp.macosx-10.13-intel-2.7/src/MD2.o
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    error: command 'cc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-GShbC0/pycryptodome/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-yDSS3H-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-GShbC0/pycryptodome/
```
Error occurs with and without root permissions, and using either pip or pip3. My MacOS version is 10.13.1

**Comment by peterorlowsky** [comment]
I get another error while installing on Sierra with python 3.6.4

```   Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/zs/8b1w_fpx1_s5k8j0f6bdn6y80000gr/T/pip-install-q_gtdcgv/pdfminer/setup.py", line 3, in <module>
        from pdfminer import __version__
      File "/private/var/folders/zs/8b1w_fpx1_s5k8j0f6bdn6y80000gr/T/pip-install-q_gtdcgv/pdfminer/pdfminer/__init__.py", line 5
        print __version__
                        ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print(int __version__)?
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/zs/8b1w_fpx1_s5k8j0f6bdn6y80000gr/T/pip-install-q_gtdcgv/pdfminer/
```
Has anyone made it work on MacOS yet?

**Comment by pietermarsman** [comment]
The original issue looks like it has something to do with os permissions. While this might be difficult to fix, my guess is that it has nothing to do with pdfminer.six. 

Also this issue is old and probably outdated. 

So, I am going to close this issue. If it still persists and you need our help, feel free to reopen.
