### ISSUE TITLE
LTImage.stream.get_data() extracts broken data from PDF contains CCITTFax image

### ISSUE THREAD

**Issue by atuyosi** [pdfminer/pdfminer.six#144]
I tried to extract image from pdf, but wrong data extracted.

The image data seems to be in CCITTFax format, but it looks like decoding failed.

```python
from pdfminer.pdfparser import PDFParser
from pdfminer.pdfdocument import PDFDocument
from pdfminer.pdfpage import PDFPage
from pdfminer.pdfpage import PDFTextExtractionNotAllowed
from pdfminer.pdfinterp import PDFResourceManager
from pdfminer.pdfinterp import PDFPageInterpreter
from pdfminer.pdfdevice import PDFDevice
# from pdfminer.layout import LAParams
from pdfminer.layout import LAParams, LTTextBox, LTTextLine, LTFigure, LTImage, LTChar
from pdfminer.converter import PDFPageAggregator

import os,sys,io
from PIL import Image

# Set parameters for analysis.
laparams = LAParams()

rsrcmgr = PDFResourceManager()

# Create a PDF page aggregator object.
device = PDFPageAggregator(rsrcmgr, laparams=laparams)
interpreter = PDFPageInterpreter(rsrcmgr, device)


# Open a PDF file.
fp = open("060719.pdf",'rb')

# Create a PDF parser object associated with the file object.
parser = PDFParser(fp)
# Create a PDF document object that stores the document structure.
# Supply the password for initialization.
document = PDFDocument(parser)

for p, page in enumerate(PDFPage.create_pages(document)):
    interpreter.process_page(page)
    # receive the LTPage object for the page.
    layout = device.get_result()

    for node in layout:
        # print(type(node))

        if isinstance(node,LTFigure):
            for n in node:
                #print(" {}".format(type(n)))

                if n.stream:
                    buffer = io.BytesIO(n.stream.get_data())

                    # with open("test_data_{}.img".format(p),'wb') as fp :
                    #    fp.write(buffer.read())

                    pillow_object = Image.open(buffer)
                    pillow_object.save("test_image_{}".format(p), png)
```

the return value of `stream.get_data() ` does'nt valid image data. It seems decode error.

The error message is below:
```
Traceback (most recent call last):
  File "/Users/atuyosi/PycharmProjects/pdf_outline/extract_image_from_pdf.py", line 58, in <module>
    pillow_object = Image.open(buffer)
  File "/Users/atuyosi/PycharmProjects/pdf_outline/venv/lib/python3.6/site-packages/PIL/Image.py", line 2590, in open
    % (filename if filename else fp))
OSError: cannot identify image file <_io.BytesIO object at 0x1021996d0>
```

mutool's output are below:

```
$ mutool info 060719.pdf
/060719.pdf:

PDF-1.4
Info object (1 0 R):
<<>>
Pages: 8

Retrieving info from pages 1-8...
Mediaboxes (2):
	1	(4 0 R):	[ 0 0 593.27999 842.04 ]
	2	(5 0 R):	[ 0 0 590.39999 842.04 ]

Images (8):
	1	(4 0 R):	[ CCITTFax ] 1648x2339 1bpc DevGray (12 0 R)
	2	(5 0 R):	[ CCITTFax ] 1640x2339 1bpc DevGray (16 0 R)
	3	(6 0 R):	[ CCITTFax ] 1648x2339 1bpc DevGray (20 0 R)
	4	(7 0 R):	[ CCITTFax ] 1648x2339 1bpc DevGray (24 0 R)
	5	(8 0 R):	[ CCITTFax ] 1648x2339 1bpc DevGray (28 0 R)
	6	(9 0 R):	[ CCITTFax ] 1648x2339 1bpc DevGray (32 0 R)
	7	(10 0 R):	[ CCITTFax ] 1648x2339 1bpc DevGray (36 0 R)
	8	(11 0 R):	[ CCITTFax ] 1648x2339 1bpc DevGray (40 0 R)
```

[060719.pdf](https://github.com/pdfminer/pdfminer.six/files/1966442/060719.pdf)

**Comment by pietermarsman** [comment]
I get good results when I use the pdf2txt.py utility. For example, if you want to write the images to the "output" directory: 

```commandline
python tools/pdf2txt.py --output-dir output 060719.pdf
```

In your example you are using the composable api. It looks pretty good, but you need to give PIL some specific hints on how to read the image, i.e. tell it that the images is black-or-white. I got it to work with the following code: 

```python
from PIL import Image

from pdfminer.converter import PDFPageAggregator
from pdfminer.pdfdocument import PDFDocument
from pdfminer.pdfinterp import PDFPageInterpreter
from pdfminer.pdfinterp import PDFResourceManager
from pdfminer.pdfpage import PDFPage
from pdfminer.pdfparser import PDFParser

with open('samples/contrib/issue-00144-extract-ccittfax-image.pdf', 'rb') as fp:
    parser = PDFParser(fp)
    doc = PDFDocument(parser)
    rsrcmgr = PDFResourceManager()
    device = PDFPageAggregator(rsrcmgr)
    interpreter = PDFPageInterpreter(rsrcmgr, device)
    for page in PDFPage.create_pages(doc):
        interpreter.process_page(page)
        layout = device.get_result()
        for figure in layout:
            for image_object in figure:
                image = Image.frombytes('1', image_object.srcsize, image_object.stream.get_data(), 'raw')
                with open(image_object.name + '.bmp', 'wb') as fp:
                    image.save(fp)
```

**Comment by apdullahyayik** [comment]
Still ValueError: not enough image data occurs. 
Data return from image_object.stream.get_data() doesnt satisfy the size that should be. @pietermarsman

**Comment by pietermarsman** [comment]
What code are you using? Which pdf are you testing on?

**Comment by saadcovera** [comment]
> 

In this case.. i would suggest using Image.open(image.stream.getdata()) ..the reason would be that its might be returning a loseless compression image like JPEG instead of RAW png
