### ISSUE TITLE
Incorrect parsing of filenames in file specifications

### ISSUE THREAD

**Issue by davidtr1037** [pdfminer/pdfminer.six#152]
There is an issue with parsing filenames of file specifications:
For example, when I run:
```
dumppdf.py -E /tmp/ sample.pdf
```
I get:
```
Traceback (most recent call last):
  File "./build/scripts-2.7/dumppdf.py", line 275, in <module>
    if __name__ == '__main__': sys.exit(main(sys.argv))
  File "./build/scripts-2.7/dumppdf.py", line 272, in main
    dumpall=dumpall, codec=codec, extractdir=extractdir)
  File "./build/scripts-2.7/dumppdf.py", line 200, in extractembedded
    extract1(obj)
  File "./build/scripts-2.7/dumppdf.py", line 173, in extract1
    filename = os.path.basename(obj['UF'] or obj['F'])
KeyError: 'UF'
```

Possible fix:
```
filename = obj.get('UF') or obj.get('F') or <some_default_string>
```
The pdf is attached: 
[7c127eb6889074efbfac63d35ba0b69cfae22d56bfa2755ef0e925b6c032c4b0.pdf](https://github.com/pdfminer/pdfminer.six/files/2087110/7c127eb6889074efbfac63d35ba0b69cfae22d56bfa2755ef0e925b6c032c4b0.pdf)

**Comment by pietermarsman** [comment]
Thanks for your issue! I've created #338 to fix this. Do you have more pdf's with embedded images? Could you check if the PR code works for those?
