### ISSUE TITLE
Parsing issue

### ISSUE THREAD

**Issue by davidtr1037** [pdfminer/pdfminer.six#153]
There is a parsing issue when trying to extract objects with dumppdf.py:
```
dumppdf.py -E /tmp/ sample.pdf
```
The trace:
```
Traceback (most recent call last):
  File "./build/scripts-2.7/dumppdf.py", line 275, in <module>
    if __name__ == '__main__': sys.exit(main(sys.argv))
  File "./build/scripts-2.7/dumppdf.py", line 272, in main
    dumpall=dumpall, codec=codec, extractdir=extractdir)
  File "./build/scripts-2.7/dumppdf.py", line 195, in extractembedded
    doc = PDFDocument(parser, password)
  File "/usr/local/lib/python2.7/dist-packages/pdfminer.six-20170720-py2.7.egg/pdfminer/pdfdocument.py", line 560, in __init__
    self.read_xref_from(parser, pos, self.xrefs)
  File "/usr/local/lib/python2.7/dist-packages/pdfminer.six-20170720-py2.7.egg/pdfminer/pdfdocument.py", line 800, in read_xref_from
    xref.load(parser)
  File "/usr/local/lib/python2.7/dist-packages/pdfminer.six-20170720-py2.7.egg/pdfminer/pdfdocument.py", line 237, in load
    (_, stream) = parser.nextobject()
  File "/usr/local/lib/python2.7/dist-packages/pdfminer.six-20170720-py2.7.egg/pdfminer/psparser.py", line 616, in nextobject
    self.do_keyword(pos, token)
  File "/usr/local/lib/python2.7/dist-packages/pdfminer.six-20170720-py2.7.egg/pdfminer/pdfparser.py", line 78, in do_keyword
    ((_, objid), (_, genno)) = self.pop(2)
ValueError: need more than 1 value to unpack
```
The pdf is attached:
[8a100aaa2816037e195800580507cefa1d1873385ef9dc43598712f5173fe5eb.pdf](https://github.com/pdfminer/pdfminer.six/files/2087112/8a100aaa2816037e195800580507cefa1d1873385ef9dc43598712f5173fe5eb.pdf)

**Comment by pietermarsman** [comment]
Opening the pdf in a text editor and saving it again solves the problem. I think this has something to do with newline characters. Your PDF uses carriages returns. 

(I'm aware that this is not really an answer to your question, but I'm just trying to figure out what could be causing this issue).

**Comment by pietermarsman** [comment]
You could also repair your pdf using mutools: 

```commandline
$ mutool clean 8a100aaa2816037e195800580507cefa1d1873385ef9dc43598712f5173fe5eb.pdf clean.pdf
error: expected generation number (0 ? obj)
warning: trying to repair broken xref
warning: repairing PDF document
warning: line feed missing after stream begin marker (208 0 R)
```
