### ISSUE TITLE
Specifying headers raises PDFSyntaxError

### ISSUE THREAD

**Issue by micmalti** [pdfminer/pdfminer.six#185]
I am trying to parse several online pdfs from Researchgate so I've decided to use a rotating proxy and a rotating header in the Requests function to avoid delay issues and redirections.  However, this raised an error:
```
Traceback (most recent call last):
  File "pdf_parser.py", line 203, in <module>
    pdf_data().pdf_parser(line,100)
  File "pdf_parser.py", line 110, in pdf_parser
    rawtext = self.pdf_text(line,n)
  File "pdf_parser.py", line 66, in pdf_text
    for page in PDFPage.get_pages(fp, pagenos=set(), caching=True, check_extractable=True):
  File "/home/micmalti/anaconda3/lib/python3.6/site-packages/pdfminer/pdfpage.py", line 129, in get_pages
    doc = PDFDocument(parser, password=password, caching=caching)
  File "/home/micmalti/anaconda3/lib/python3.6/site-packages/pdfminer/pdfdocument.py", line 585, in __init__
    raise PDFSyntaxError('No /Root object! - Is this really a PDF?')
pdfminer.pdfparser.PDFSyntaxError: No /Root object! - Is this really a PDF?
```
Headers originate from the fake_useragent module and each is stated in the Requests function using the following code: 
`header = UserAgent()`
`headers = {'User-Agent':str(header.random)}`
`requests.get(url, headers=headers, proxies={"http": proxy, "https": proxy}, timeout=30)`

**Comment by micmalti** [comment]
**Update:**

I discovered that I was closing BytesIO() before StringIO() and TextConverter(). Just for the sake of clarity, this is how to parse a pdf from a url:

`pdf = requests.get(url)
 fp = BytesIO(pdf.content)
 outfp = StringIO()
 rsrcmgr = PDFResourceManager()
 device = TextConverter(rsrcmgr, outfp, codec="utf-8", laparams=LAParams())
 interpreter = PDFPageInterpreter(rsrcmgr, device) 
 for page in PDFPage.get_pages(fp, pagenos=set(), caching=True, check_extractable=True):
   interpreter.process_page(page)
 device.close()
 text = outfp.getvalue()
 outfp.close()
 fp.close()`
