### ISSUE TITLE
struct.error: unpack requires a buffer of 8 bytes

### ISSUE THREAD

**Issue by FliegendeWurst** [pdfminer/pdfminer.six#193]
When I try to process [this pdf](https://github.com/pdfminer/pdfminer.six/files/2474355/v_schueler_heute.6.pdf) using pdf2txt.py, I get this error:

```
Traceback (most recent call last):
  File "pdf2txt.py", line 136, in <module>
    if __name__ == '__main__': sys.exit(main())
  File "pdf2txt.py", line 131, in main
    outfp = extract_text(**vars(A))
  File "pdf2txt.py", line 63, in extract_text
    pdfminer.high_level.extract_text_to_fp(fp, **locals())
  File "/home/arne/.local/lib/python3.6/site-packages/pdfminer/high_level.py", line 83, in extract_text_to_fp
    interpreter.process_page(page)    
  File "/home/arne/.local/lib/python3.6/site-packages/pdfminer/pdfinterp.py", line 852, in process_page
    self.render_contents(page.resources, page.contents, ctm=ctm)
  File "/home/arne/.local/lib/python3.6/site-packages/pdfminer/pdfinterp.py", line 862, in render_contents
    self.init_resources(resources)
  File "/home/arne/.local/lib/python3.6/site-packages/pdfminer/pdfinterp.py", line 362, in init_resources
    self.fontmap[fontid] = self.rsrcmgr.get_font(objid, spec)
  File "/home/arne/.local/lib/python3.6/site-packages/pdfminer/pdfinterp.py", line 212, in get_font
    font = self.get_font(None, subspec)
  File "/home/arne/.local/lib/python3.6/site-packages/pdfminer/pdfinterp.py", line 203, in get_font
    font = PDFCIDFont(self, spec)
  File "/home/arne/.local/lib/python3.6/site-packages/pdfminer/pdffont.py", line 667, in __init__
    BytesIO(self.fontfile.get_data()))
  File "/home/arne/.local/lib/python3.6/site-packages/pdfminer/pdffont.py", line 386, in __init__
    (ntables, _1, _2, _3) = struct.unpack('>HHHH', fp.read(8))
struct.error: unpack requires a buffer of 8 bytes
```

**Comment by panoptikum** [comment]
I second this https://github.com/pdfminer/pdfminer.six/issues/200

**Comment by pietermarsman** [comment]
With the latest version of pdfminer.six I can process this pdf without errors. 

The output only contains `(cid:xxx)` values though. I did some looking around and it looks like the embedded font specification cannot be parsed. It has a `FlateDecode` filter (see pdf reference section 3.3) but an error is raised (and excepted) when pdfminer.six tries to `zlib.decompress()` it.

**Comment by pietermarsman** [comment]
If you clean this pdf with `mutools clean -ldcs` the characters become readable.

**Comment by pietermarsman** [comment]
I'm closing this as the original issue is resolved.
