### ISSUE TITLE
Failure to read PDF file

### ISSUE THREAD

**Issue by pombredanne** [pdfminer/pdfminer.six#209]
This https://github.com/mstamy2/PyPDF2/blob/master/PDF_Samples/AutoCad_Diagram.pdf open OK in evince on Linux. It fails to read with pdfminer.six (latest version as of today) with this error trace in ScanCode:
```
Traceback (most recent call last):
  File "/tmp/scancode-toolkit/src/scancode/interrupt.py", line 91, in interruptible
    return NO_ERROR, func(*(args or ()), **(kwargs or {}))
  File "/tmp/scancode-toolkit/src/scancode/api.py", line 172, in get_licenses
    for match in idx.match(location=location, min_score=min_score, **kwargs):
  File "/tmp/scancode-toolkit/src/licensedcode/index.py", line 564, in match
    text_line_threshold=15, bin_line_threshold=50)
  File "/tmp/scancode-toolkit/src/licensedcode/query.py", line 119, in build_query
    if not T.contains_text:
  File "/tmp/scancode-toolkit/src/typecode/contenttype.py", line 506, in contains_text
    elif self.is_pdf and not self.is_pdf_with_text:
  File "/tmp/scancode-toolkit/src/typecode/contenttype.py", line 490, in is_pdf_with_text
    doc = PDFDocument(parser)
  File "/tmp/scancode-toolkit/local/lib/python2.7/site-packages/pdfminer/pdfdocument.py", line 566, in __init__
    xref.load(parser)
  File "/tmp/scancode-toolkit/local/lib/python2.7/site-packages/pdfminer/pdfdocument.py", line 195, in load
    (_, obj) = parser.nextobject()
  File "/tmp/scancode-toolkit/local/lib/python2.7/site-packages/pdfminer/psparser.py", line 597, in nextobject
    raise PSSyntaxError('Invalid dictionary construct: %r' % objs)
PSSyntaxError: Invalid dictionary construct: [/'Type', /'XObject', /'Subtype', /'Image', /'Width', 1175, /'Height', 1326, /'ColorSpace', [/'Indexed', /'DeviceRGB\x00255', '\x00\x00\x00\x80\x00\x00\x00\x80\x00\x80\x80\x00\x00\x00\x80\x80\x00\x80\x00\x80\x80\xc0\xc0\xc0\xc0\xdc\xc0\xa6\xca\xf0\x00\x00\x00\x00\x003\x00\x00f\x00\x00\x99\x00\x00\xcc\x00\x00\xff\x003\x00\x0033\x003f\x003\x99\x003\xcc\x003\xff\x00f\x00\x00f3\x00ff\x00f\x99\x00f\xcc\x00f\xff\x00\x99\x00\x00\x993\x00\x99f\x00\x99\x99\x00\x99\xcc\x00\x99\xff\x00\xcc\x00\x00\xcc3\x00\xccf\x00\xcc\x99\x00\xcc\xcc\x00\xcc\xff\x00\xff\x00\x00\xff3\x00\xfff\x00\xff\x99\x00\xff\xcc\x00\xff\xff3\x00\x003\x0033\x00f3\x00\x993\x00\xcc3\x00\xff33\x0033333f33\x9933\xcc33\xff3f\x003f33ff3f\x993f\xcc3f\xff3\x99\x003\x9933\x99f3\x99\x993\x99\xcc3\x99\xff3\xcc\x003\xcc33\xccf3\xcc\x993\xcc\xcc3\xcc\xff3\xff\x003\xff33\xfff3\xff\x993\xff\xcc3\xff\xfff\x00\x00f\x003f\x00ff\x00\x99f\x00\xccf\x00\xfff3\x00f33f3ff3\x99f3\xccf3\xffff\x00ff3fffff\x99ff\xccff\xfff\x99\x00f\x993f\x99ff\x99\x99f\x99\xccf\x99\xfff\xcc\x00f\xcc3f\xccff\xcc\x99f\xcc\xccf\xcc\xfff\xff\x00f\xff3f\xffff\xff\x99f\xff\xccf\xff\xff\x99\x00\x00\x99\x003\x99\x00f\x99\x00\x99\x99\x00\xcc\x99\x00\xff\x993\x00\x9933\x993f\x993\x99\x993\xcc\x993\xff\x99f\x00\x99f3\x99ff\x99f\x99\x99f\xcc\x99f\xff\x99\x99\x00\x99\x993\x99\x99f\x99\x99\x99\x99\x99\xcc\x99\x99\xff\x99\xcc\x00\x99\xcc3\x99\xccf\x99\xcc\x99\x99\xcc\xcc\x99\xcc\xff\x99\xff\x00\x99\xff3\x99\xfff\x99\xff\x99\x99\xff\xcc\x99\xff\xff\xcc\x00\x00\xcc\x003\xcc\x00f\xcc\x00\x99\xcc\x00\xcc\xcc\x00\xff\xcc3\x00\xcc33\xcc3f\xcc3\x99\xcc3\xcc\xcc3\xff\xccf\x00\xccf3\xccff\xccf\x99\xccf\xcc\xccf\xff\xcc\x99\x00\xcc\x993\xcc\x99f\xcc\x99\x99\xcc\x99\xcc\xcc\x99\xff\xcc\xcc\x00\xcc\xcc3\xcc\xccf\xcc\xcc\x99\xcc\xcc\xcc\xcc\xcc\xff\xcc\xff\x00\xcc\xff3\xcc\xfff\xcc\xff\x99\xcc\xff\xcc\xcc\xff\xff\xff\x00\x00\xff\x003\xff\x00f\xff\x00\x99\xff\x00\xcc\xff\x00\xff\xff3\x00\xff33\xff3f\xff3\x99\xff3\xcc\xff3\xff\xfff\x00\xfff3\xffff\xfff\x99\xfff\xcc\xfff\xff\xff\x99\x00\xff\x993\xff\x99f\xff\x99\x99\xff\x99\xcc\xff\x99\xff\xff\xcc\x00\xff\xcc3\xff\xccf\xff\xcc\x99\xff\xcc\xcc\xff\xcc\xff\xff\xff\x00\xff\xff3\xff\xfff\xff\xff\x99\xff\xff\xcc\xff\xff\xff\x00\x00\x00\r\r\r\x1a\x1a\x1a(((555CCCPPP]]]kkkxxx\x86\x86\x86\x93\x93\x93\xa1\xa1\xa1\xae\xae\xae\xbb\xbb\xbb\xc9\xc9\xc9\xd6\xd6\xd6\xe4\xe4\xe4\xf1\xf1\xf1\xff\xff\xff\xff\xfb\xf0\xa0\xa0\xa4\x80\x80\x80\xff\x00\x00\x00\xff\x00\xff\xff\x00\x00\x00\xff\xff\x00\xff\x00\xff\xff\xff\xff\xff'], /'\x00', /'BitsPerComponent', 8, /'Length', 20902, /'Filter', /'FlateDecode', /'DecodeParms', {'Colors': 1, 'Columns': 1175, 'Predictor': 15, 'BitsPerComponent': 8}]
```

**Comment by ganeshtata** [comment]
@pombredanne Did the same PDF work with the previous version of pdfminer.six?

**Comment by pietermarsman** [comment]
The error is a dictionary specification with an uneven number of items. The dictionary should contain an even number of items, because it alternates keys and values. I think the error is the `/'\x00'` after the long `ColorSpace` value and before the `BitsPerComponent`. This byte should either be part of the stream or not there at all. If you remove it (in two places) the PDF processes fine. 

I was also able to use `mutools clean` to fix this error.
