### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'.

### ISSUE THREAD

**Issue by wangxiaodiu** [pdfminer/pdfminer.six#277]
Error information:
`Traceback (most recent call last):
  File "./tools/pdf2txt.py", line 136, in <module>
    if __name__ == '__main__': sys.exit(main())
  File "./tools/pdf2txt.py", line 131, in main
    outfp = extract_text(**vars(A))
  File "./tools/pdf2txt.py", line 63, in extract_text
    pdfminer.high_level.extract_text_to_fp(fp, **locals())
  File "/home/ln932/github/niu/pdfminer.six/pdfminer/high_level.py", line 82, in extract_text_to_fp
    interpreter.process_page(page)    
  File "/home/ln932/github/niu/pdfminer.six/pdfminer/pdfinterp.py", line 852, in process_page
    self.render_contents(page.resources, page.contents, ctm=ctm)
  File "/home/ln932/github/niu/pdfminer.six/pdfminer/pdfinterp.py", line 864, in render_contents
    self.execute(list_value(streams))
  File "/home/ln932/github/niu/pdfminer.six/pdfminer/pdfinterp.py", line 888, in execute
    func(*args)
  File "/home/ln932/github/niu/pdfminer.six/pdfminer/pdfinterp.py", line 801, in do_EI
    if 'W' in obj and 'H' in obj:
TypeError: a bytes-like object is required, not 'str'`

Test file:
[Li_Persistence-based_Structural_Recognition_2014_CVPR_paper.pdf](https://github.com/pdfminer/pdfminer.six/files/3416394/Li_Persistence-based_Structural_Recognition_2014_CVPR_paper.pdf)

Test command: pdf2txt.py, in python 3.7

**Comment by pietermarsman** [comment]
Hi @wangxiaodiu, thanks for your bug report. 

I can replicate this error. The error is in the `do_EI()` function. This function deals with rendering images. During parsing the pdf it is called numerous times with a `PDFStream` as `obj` argument. The error arrises when the function is called with a bytes-string instead of a `PDFStream`.

**Comment by pietermarsman** [comment]
Fixed in #451.
