### ISSUE TITLE
Output type TAG error

### ISSUE THREAD

**Issue by diegodelima** [pdfminer/pdfminer.six#375]
The command: 
`pdf2txt.py-3 -t tag PDFFILE.pdf`
Always gives the following error: AttributeError: 'dict' object has no attribute 'iteritems'

PDF test file attached:
[20200213CAPDJETJRJ_298.pdf](https://github.com/pdfminer/pdfminer.six/files/4199179/20200213CAPDJETJRJ_298.pdf)

Using python 3.6 on CentOS 7.

Full error:
<page id="0" bbox="0.000,0.000,595.320,841.920" rotate="0">Traceback (most recent call last):
  File "/usr/bin/pdf2txt.py-3", line 126, in <module>
    if __name__ == '__main__': sys.exit(main())
  File "/usr/bin/pdf2txt.py-3", line 121, in main
    outfp = extract_text(**vars(A))
  File "/usr/bin/pdf2txt.py-3", line 61, in extract_text
    pdfminer.high_level.extract_text_to_fp(fp, **locals())
  File "/usr/lib/python3.6/site-packages/pdfminer/high_level.py", line 82, in extract_text_to_fp
    interpreter.process_page(page)    
  File "/usr/lib/python3.6/site-packages/pdfminer/pdfinterp.py", line 835, in process_page
    self.render_contents(page.resources, page.contents, ctm=ctm)
  File "/usr/lib/python3.6/site-packages/pdfminer/pdfinterp.py", line 847, in render_contents
    self.execute(list_value(streams))
  File "/usr/lib/python3.6/site-packages/pdfminer/pdfinterp.py", line 871, in execute
    func(*args)
  File "/usr/lib/python3.6/site-packages/pdfminer/pdfinterp.py", line 670, in do_BDC
    self.device.begin_tag(tag, props)
  File "/usr/lib/python3.6/site-packages/pdfminer/pdfdevice.py", line 166, in begin_tag
    in sorted(props.iteritems()))
AttributeError: 'dict' object has no attribute 'iteritems'

**Comment by pietermarsman** [comment]
Looks like you are using an old version of pdfminer.six. Could you update to the newest version and try again?

**Comment by diegodelima** [comment]
Updated to latest version, but I got a different problem (see below). The problem seems to happen only with the "-t tag" argument. Additionally, if a use "pip2" and "python2", it works fine with the "-t tag" argument. I guess it's something with the "tag" output and python3 only.

# pip3 install pdfminer.six
...
# pip3 show -f pdfminer.six
Name: pdfminer.six
Version: 20200124
...

# python3 --version
Python 3.6.8

# python3 /usr/local/bin/pdf2txt.py -t tag /tmp/doczy.caselaw.pdf.819.0.2019-12-12.510.pdf
<page id="0" bbox="0.000,0.000,595.320,841.920" rotate="0"><Artifact Attached="[/&#x27;Top&#x27;]" Subtype="/&#x27;Header&#x27;" Type="/&#x27;Pagination&#x27;">Traceback (most recent call last):
  File "/usr/local/bin/pdf2txt.py", line 188, in <module>
    sys.exit(main())
  File "/usr/local/bin/pdf2txt.py", line 182, in main
    outfp = extract_text(**vars(A))
  File "/usr/local/bin/pdf2txt.py", line 56, in extract_text
    pdfminer.high_level.extract_text_to_fp(fp, **locals())
  File "/usr/local/lib/python3.6/site-packages/pdfminer/high_level.py", line 85, in extract_text_to_fp
    interpreter.process_page(page)
  File "/usr/local/lib/python3.6/site-packages/pdfminer/pdfinterp.py", line 895, in process_page
    self.render_contents(page.resources, page.contents, ctm=ctm)
  File "/usr/local/lib/python3.6/site-packages/pdfminer/pdfinterp.py", line 908, in render_contents
    self.execute(list_value(streams))
  File "/usr/local/lib/python3.6/site-packages/pdfminer/pdfinterp.py", line 933, in execute
    func(*args)
  File "/usr/local/lib/python3.6/site-packages/pdfminer/pdfinterp.py", line 803, in do_TJ
    self.graphicstate.copy())
  File "/usr/local/lib/python3.6/site-packages/pdfminer/pdfdevice.py", line 159, in render_string
    self.outfp.write(utils.enc(text))
TypeError: a bytes-like object is required, not 'str'

**Comment by colegleason** [comment]
I am encountering the same error, but have not found the requisite bug.

**Comment by zhijcao** [comment]
I have this problem too, is there any update?
