### ISSUE TITLE
What does PDFDocument's get_dest method do?

### ISSUE THREAD

**Issue by SystemLight** [pdfminer/pdfminer.six#378]
**Describe the bug**
Traceback (most recent call last):
  File "D:/Python/untitled1/mainTwo.py", line 11, in <module>
    document.get_dest("pm")
  File "C:\Users\Lisys\AppData\Local\Programs\Python\Python35\lib\site-packages\pdfminer\pdfdocument.py", line 752, in get_dest
    raise PDFDestinationNotFound(name)
pdfminer.pdfdocument.PDFDestinationNotFound: pm

**To Reproduce**
parse = PDFParser(open("./data/data.pdf", 'rb'))
document = PDFDocument(parse)
document.get_dest("pm")

**Expected behavior**
I don't understand this method.What can it do?

**Comment by SystemLight** [comment]
Solve： https://docs.adobe.com/content/help/en/experience-platform/rtcdp/destinations/destinations-overview.html
