### ISSUE TITLE
Exception when parsing PDF 'portfolios'

### ISSUE THREAD

**Issue by jjhuff** [pdfminer/pdfminer.six#403]
Example URL: https://www.accessdata.fda.gov/cdrh_docs/pdf17/K171077.pdf

Backtrace:
```
  File "/usr/local/lib/python3.7/site-packages/pdfminer/pdfpage.py", line 127, in get_pages
    doc = PDFDocument(parser, password=password, caching=caching)
  File "/usr/local/lib/python3.7/site-packages/pdfminer/pdfdocument.py", line 554, in __init__
    xref.load(parser)
  File "/usr/local/lib/python3.7/site-packages/pdfminer/pdfdocument.py", line 177, in load
    (_, obj) = parser.nextobject()
  File "/usr/local/lib/python3.7/site-packages/pdfminer/psparser.py", line 610, in nextobject
    self.do_keyword(pos, token)
  File "/usr/local/lib/python3.7/site-packages/pdfminer/pdfparser.py", line 73, in do_keyword
    (objid, genno) = (int(objid), int(genno))
TypeError: int() argument must be a string, a byte
```

I'm not specifically worried about parsing the PDF contents, but if I could extract the "For the best experience, open this PDF portfolio" string, I can use that to detect the portfilio and use `pdfdetatch`

**Comment by pietermarsman** [comment]
Hi @jjhuff, thanks for your question! 

Which version of pdfminer.six are you using? And what command are you using?

**Comment by jjhuff** [comment]
I was using 20200124
The code is more or less this, but I believe it should repo with pdf2txt
```
    laparams = LAParams()
    rsrcmgr = PDFResourceManager()
    with io.StringIO() as outfp:
        device = TextConverter(rsrcmgr, outfp, laparams=laparams)
        interpreter = PDFPageInterpreter(rsrcmgr, device)
        for page in PDFPage.get_pages(fp):
            interpreter.process_page(page)
        device.close()
        text = outfp.getvalue()
```

**Comment by pietermarsman** [comment]
I can replicate this issue using `pdf2txt.py`. The full error I get is: 

```
Traceback (most recent call last):
  File "tools/pdf2txt.py", line 188, in <module>
    sys.exit(main())
  File "tools/pdf2txt.py", line 182, in main
    outfp = extract_text(**vars(A))
  File "tools/pdf2txt.py", line 56, in extract_text
    pdfminer.high_level.extract_text_to_fp(fp, **locals())
  File "/home/pieter/projects/pdfminer-upstream/pdfminer/high_level.py", line 78, in extract_text_to_fp
    for page in PDFPage.get_pages(inf,
  File "/home/pieter/projects/pdfminer-upstream/pdfminer/pdfpage.py", line 127, in get_pages
    doc = PDFDocument(parser, password=password, caching=caching)
  File "/home/pieter/projects/pdfminer-upstream/pdfminer/pdfdocument.py", line 554, in __init__
    xref.load(parser)
  File "/home/pieter/projects/pdfminer-upstream/pdfminer/pdfdocument.py", line 177, in load
    (_, obj) = parser.nextobject()
  File "/home/pieter/projects/pdfminer-upstream/pdfminer/psparser.py", line 610, in nextobject
    self.do_keyword(pos, token)
  File "/home/pieter/projects/pdfminer-upstream/pdfminer/pdfparser.py", line 73, in do_keyword
    (objid, genno) = (int(objid), int(genno))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'PSKeyword'
```

**Comment by pietermarsman** [comment]
Fixed in the current release.

Was fixed by PR https://github.com/pdfminer/pdfminer.six/pull/684. Probably there is an error in one of the objects that is listed by the fallback xref added by pdfminer.six, but is not used anywhere in the PDF and therefore is not in the actual xref in the PDF document.
