### ISSUE TITLE
Failed to get text from pdfs from same publisher. Got KeyError: 'N'

### ISSUE THREAD

**Issue by timtangcoding** [pdfminer/pdfminer.six#445]
I'm getting the following error when running pdf2txt.py on certain pdfs. I've noticed that it seems the error that I encountered are from the same publisher (However not every PDF from the publisher).  
Even if I tried to check for the error and avoid crashing. There seems to be no content obtained from the PDF. 
How could a PDF file so widely distributed results so differently? 
Also, as the PDF is copyright protected. How could I provide a sample to this repo?

Thanks!

Traceback (most recent call last):
  File "tools/pdf2txt.py", line 197, in <module>
    sys.exit(main())
  File "tools/pdf2txt.py", line 191, in main
    outfp = extract_text(**vars(A))
  File "tools/pdf2txt.py", line 59, in extract_text
    pdfminer.high_level.extract_text_to_fp(fp, **locals())
  File "/Users/user/Documents/works/python/pdfminer/pdfminer.six/venv/lib/python3.6/site-packages/pdfminer/high_level.py", line 86, in extract_text_to_fp
    interpreter.process_page(page)
  File "/Users/user/Documents/works/python/pdfminer/pdfminer.six/venv/lib/python3.6/site-packages/pdfminer/pdfinterp.py", line 895, in process_page
    self.render_contents(page.resources, page.contents, ctm=ctm)
  File "/Users/user/Documents/works/python/pdfminer/pdfminer.six/venv/lib/python3.6/site-packages/pdfminer/pdfinterp.py", line 906, in render_contents
    self.init_resources(resources)
  File "/Users/user/Documents/works/python/pdfminer/pdfminer.six/venv/lib/python3.6/site-packages/pdfminer/pdfinterp.py", line 357, in init_resources
    self.csmap[csid] = get_colorspace(resolve1(spec))
  File "/Users/user/Documents/works/python/pdfminer/pdfminer.six/venv/lib/python3.6/site-packages/pdfminer/pdfinterp.py", line 340, in get_colorspace
    return PDFColorSpace(name, stream_value(spec[1])['N'])
  File "/Users/user/Documents/works/python/pdfminer/pdfminer.six/venv/lib/python3.6/site-packages/pdfminer/pdftypes.py", line 219, in __getitem__
    return self.attrs[name]
KeyError: 'N'

**Comment by pietermarsman** [comment]
Hi @timtangcoding, can you share the code you are using? And also include the PDF that raises the KeyError. That way we can reproduce the issue.

**Comment by timtangcoding** [comment]
I was running the sample code pdf2txt.py on some PDF with copyright.

The error suggest a key "N" is expected when it's absent.  Also, even the exception is handled, the content could not be extracted, except for the content page. So The it looks like the PDF might be structured differently from the standard pdfminer based,

However, the PDF was some ebook and is fine when opened with different PDF reader. So it was strange how could some file not conforming to standard could be published widely and read by so many PDF programs...

I need to see if there other sample that have would cause same exception and could be shared.

**Comment by pietermarsman** [comment]
It will be great if you can provide a sample PDF. Without such an example it is difficult to understand and fix the problem, so we close bug reports without an example PDF.

**Comment by pietermarsman** [comment]
Closing this because of inactivity

**Comment by lroberts7** [comment]
I had left my comments on another issue that also has this error but it seems this closed issue is more relevant so I will link:

https://github.com/pdfminer/pdfminer.six/issues/559#issuecomment-1432275765

ultimately I'm not sure the root cause if it is pdf source error or a bug, but I see cases where RGB colors in 
`stream_value(spec[1])` call ***do not*** have the `'N'` key which causes the error. For pdfs in the set I'm working with swapping with `stream_value(spec[1]).get('N', 3)` resolves the issue for me but a better solution might be found.

**Comment by lroberts7** [comment]
A pdf that is public that I can reproduce the issue with locally can be found here:

https://elibrary.tranetechnologies.com/public/trane-history/Literature/Installation/18-GJ34D1-6_03012017

reproducting code: 

```
import camelot
from pathlib import Path

p = Path("/Users/lroberts/Desktop/trane_crawled_pdfs/trane_25908572.pdf")
tables = camelot.read_pdf(ppath.name)
```

and stacktrace:

```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/opt/homebrew/lib/python3.11/site-packages/camelot/io.py", line 113, in read_pdf
    tables = p.parse(
             ^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/camelot/handlers.py", line 169, in parse
    self._save_page(self.filepath, p, tempdir)
  File "/opt/homebrew/lib/python3.11/site-packages/camelot/handlers.py", line 118, in _save_page
    layout, dim = get_page_layout(fpath)
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/camelot/utils.py", line 893, in get_page_layout
    interpreter.process_page(page)
  File "/opt/homebrew/lib/python3.11/site-packages/pdfminer/pdfinterp.py", line 997, in process_page
    self.render_contents(page.resources, page.contents, ctm=ctm)
  File "/opt/homebrew/lib/python3.11/site-packages/pdfminer/pdfinterp.py", line 1014, in render_contents
    self.init_resources(resources)
  File "/opt/homebrew/lib/python3.11/site-packages/pdfminer/pdfinterp.py", line 387, in init_resources
    colorspace = get_colorspace(resolve1(spec))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pdfminer/pdfinterp.py", line 370, in get_colorspace
    return PDFColorSpace(name, stream_value(spec[1])["N"])
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pdfminer/pdftypes.py", line 285, in __getitem__
    return self.attrs[name]
           ~~~~~~~~~~^^^^^^
KeyError: 'N'
>>> 
```
