### ISSUE TITLE
Type error 'str' does not support the buffer interface

### ISSUE THREAD

**Issue by mark-summerfield** [pdfminer/pdfminer.six#50]
The attached PDF produces this error:
```
Traceback (most recent call last):
  File "/usr/local/bin/pdf2txt.py", line 4, in <module>
    __import__('pkg_resources').run_script('pdfminer.six==20170119', 'pdf2txt.py')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.5/dist-packages/pdfminer.six-20170119-py3.5.egg/EGG-INFO/scripts/pdf2txt.py", line 127, in <module>
    if __name__ == '__main__': sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/pdfminer.six-20170119-py3.5.egg/EGG-INFO/scripts/pdf2txt.py", line 122, in main
    outfp = extract_text(**vars(A))
  File "/usr/local/lib/python3.5/dist-packages/pdfminer.six-20170119-py3.5.egg/EGG-INFO/scripts/pdf2txt.py", line 62, in extract_text
    pdfminer.high_level.extract_text_to_fp(fp, **locals())
  File "/usr/local/lib/python3.5/dist-packages/pdfminer.six-20170119-py3.5.egg/pdfminer/high_level.py", line 83, in extract_text_to_fp
    interpreter.process_page(page)    
  File "/usr/local/lib/python3.5/dist-packages/pdfminer.six-20170119-py3.5.egg/pdfminer/pdfinterp.py", line 852, in process_page
    self.render_contents(page.resources, page.contents, ctm=ctm)
  File "/usr/local/lib/python3.5/dist-packages/pdfminer.six-20170119-py3.5.egg/pdfminer/pdfinterp.py", line 862, in render_contents
    self.init_resources(resources)
  File "/usr/local/lib/python3.5/dist-packages/pdfminer.six-20170119-py3.5.egg/pdfminer/pdfinterp.py", line 362, in init_resources
    self.fontmap[fontid] = self.rsrcmgr.get_font(objid, spec)
  File "/usr/local/lib/python3.5/dist-packages/pdfminer.six-20170119-py3.5.egg/pdfminer/pdfinterp.py", line 212, in get_font
    font = self.get_font(None, subspec)
  File "/usr/local/lib/python3.5/dist-packages/pdfminer.six-20170119-py3.5.egg/pdfminer/pdfinterp.py", line 203, in get_font
    font = PDFCIDFont(self, spec)
  File "/usr/local/lib/python3.5/dist-packages/pdfminer.six-20170119-py3.5.egg/pdfminer/pdffont.py", line 672, in __init__
    CMapParser(self.unicode_map, BytesIO(strm.get_data())).run()
TypeError: a bytes-like object is required, not 'str'
```
[stamp-no.pdf](https://github.com/pdfminer/pdfminer.six/files/863883/stamp-no.pdf)

**Comment by goulu** [comment]
solved in https://github.com/pdfminer/pdfminer.six/commit/7055862eaf3e95f39f9dae33edc1e521a3186d19 
but test added with provided file fails under Linux/Travis-CI with

`PDFSyntaxError: No /Root object! - Is this really a PDF?`
