### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'float' and 'bytes'

### ISSUE THREAD

**Issue by Beants** [pdfminer/pdfminer.six#506]
**Bug report**

- Description of the bug
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/xu/Documents/HiTalentAlgorithms/parsers/parserapi.py", line 66, in parse_task
    raise err
  File "/Users/xu/Documents/HiTalentAlgorithms/parsers/parserapi.py", line 56, in parse_task
    if not (result := PDFParser(content).info):
  File "/Users/xu/Documents/HiTalentAlgorithms/parsers/lib/biz/resume_pdf/pdf_parser.py", line 28, in __init__
    self._pdf = PDF(path_or_bytes)
  File "/Users/xu/Documents/HiTalentAlgorithms/parsers/lib/datatype/pdf_structure/pdf.py", line 35, in __init__
    self._parse_objs()
  File "/Users/xu/Documents/HiTalentAlgorithms/parsers/lib/datatype/pdf_structure/pdf.py", line 64, in _parse_objs
    interpreter.process_page(page)
  File "/Users/xu/Documents/HiTalentAlgorithms/venv_parsers/lib/python3.8/site-packages/pdfminer/pdfinterp.py", line 898, in process_page
    self.render_contents(page.resources, page.contents, ctm=ctm)
  File "/Users/xu/Documents/HiTalentAlgorithms/venv_parsers/lib/python3.8/site-packages/pdfminer/pdfinterp.py", line 911, in render_contents
    self.execute(list_value(streams))
  File "/Users/xu/Documents/HiTalentAlgorithms/venv_parsers/lib/python3.8/site-packages/pdfminer/pdfinterp.py", line 936, in execute
    func(*args)
  File "/Users/xu/Documents/HiTalentAlgorithms/venv_parsers/lib/python3.8/site-packages/pdfminer/pdfinterp.py", line 773, in do_Td
    self.textstate.matrix = (a, b, c, d, tx * a + ty * c + e, tx * b + ty * d + f)
TypeError: unsupported operand type(s) for +: 'float' and 'bytes'
```
-  I'm sorry I can't provide my sample pdf file, because this is a company secret, but I can provide the file header.
  ```
  %PDF-1.3
  3 0 obj
  <</Type /Page
  /Parent 1 0 R
  /Resources 2 0 R
  /MediaBox [0 0 595.28 841.89]
  /Contents 4 0 R
  >>
  ```
  
- When this bug appears, all the parameters are as follows: <name, value, type>
  ```
  a 1 <class 'int'>
  b 0 <class 'int'>
  c 0 <class 'int'>
  d 1 <class 'int'>
  e 0 <class 'int'>
  f 0 <class 'int'>
  tx 841.89 <class 'float'>
  ty b'0, 0, 0' <class 'bytes'>
  ```
  
- I fixed this problem with this simple method, but I am not sure if this is the best solution.

  ```python
      def do_Td(self, tx, ty):
          """Move text position"""
          (a, b, c, d, e, f) = self.textstate.matrix
          if isinstance(ty,bytes):
              ty=0.
          self.textstate.matrix = (a, b, c, d, tx * a + ty * c + e, tx * b + ty * d + f)
          self.textstate.linematrix = (0, 0)
          return
  ```

**Comment by pietermarsman** [comment]
According to section 5.3.1 from the [PDF Reference](https://www.adobe.com/content/dam/acom/en/devnet/acrobat/pdfs/pdf_reference_1-7.pdf) the `Td` operator has two numerical arguments, $t_x$ and $t_y$. In your case the $t_y$ argument has value `b'0, 0, 0'`, so it cannot be converted to a number. So the PDF you are using deviates from the reference. 

Can you find and share the object that contains the `Td` text positioning operator? That should specify the $t_x$ and $t_y$ variable, and perhaps that shows some light on if and how this can be fixed.

**Comment by Beants** [comment]
I read the document, there was a problem in dealing with this line: 
`q BT 0 g 42.52 841.89 rgb(0, 0, 0) Td`
The PDF version is 1.3, but i can not find any information from the [PDF Reference13](https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDFReference13.pdf).

In the process:
* `self.argstack = [42.52, 841.89]` corresponds to 'rgb', but `len(args) == nargs` is False, so continue
* When processing the next 'Td', `self.argstack= [42.52, 841.89, b'0.0.0']`, so `args` becomes `[841.89, b '0.0.0']`

Do you need any other information, My English is not very good, please forgive me.

**Comment by pietermarsman** [comment]
The line from the document provides a bit more information:

- `q` pushes a copy of the entire graphics state onto the stack (Section 4.3.1 Graphics State Stack)
- `0 g` sets the current non-stroking  color space and current non-stroking color to black (because of the 0) (Section 4.5.3 Device Color Spaces). 
- `42.52 841.89 rgb(0, 0, 0) Td` is an erroneous attempt to move to the next line with an x and y offset. 

I'm closing this issue because there is nothing we cna do.

**Comment by Beants** [comment]
Thank you for your answer, but I think we need to add the 'skip' parameter to ensure the normal parsing of the document.
