### ISSUE TITLE
AttributeError: 'PDFParser' object has no attribute 'seek'

### ISSUE THREAD

**Issue by Ocruc28** [pdfminer/pdfminer.six#511]
**Bug report**
Environemnt:
window64--Python 3.6 + Spyder 3.2.8 + pdfminer.six-20200726

======code============
```python
import pdfminer
from pdfminer.layout import LAParams
from pdfminer.converter import PDFPageAggregator
from pdfminer.pdfpage import PDFPage
from pdfminer.layout import LTTextBoxHorizontal

import io
from pdfminer.converter import TextConverter
from pdfminer.pdfinterp import PDFPageInterpreter
from pdfminer.pdfinterp import PDFResourceManager
from pdfminer.pdfpage import PDFPage

from pdfminer.pdfdocument import PDFDocument
from pdfminer.pdfpage import PDFPage
from pdfminer.pdfparser import PDFParser
from pdfminer.pdfinterp import PDFResourceManager, PDFPageInterpreter
from pdfminer.converter import PDFPageAggregator
from pdfminer.layout import LAParams, LTTextBox, LTTextLine, LTFigure
from pdfminer.pdfparser import PDFParser
from pdfminer.pdfdocument import PDFDocument
from pdfminer.pdfpage import PDFPage
from pdfminer.pdfpage import PDFTextExtractionNotAllowed
from pdfminer.pdfinterp import PDFResourceManager
from pdfminer.pdfinterp import PDFPageInterpreter
from pdfminer.pdfdevice import PDFDevice
from pdfminer.pdfparser import PDFParser
from pdfminer.pdfdocument import PDFDocument

# # Open a PDF document.
fp = open(r'D:\HD IMO\others\Elec.pdf', 'rb')
parser = PDFParser(fp)
---------# when run this error as:   AttributeError:    'PDFParser' object has no attribute 'seek'

document = PDFDocument(parser)
---------# when run this error as:    AttributeError: 'PDFParser' object has no attribute 'revreadlines'           
```
===code============

============ error stacktrace===================

- parser = PDFParser(fp)

```
Traceback (most recent call last):
  File "<ipython-input-605-8e8497aa5264>", line 1, in <module>
    parser = PDFParser(fp)
  File "D:\anaconda3\lib\site-packages\pdfminer\pdfparser.py", line 39, in __init__
    PSStackParser.__init__(self, fp)
  File "D:\anaconda3\lib\site-packages\pdfminer\psparser.py", line 502, in __init__
    PSBaseParser.__init__(self, fp)
  File "D:\anaconda3\lib\site-packages\pdfminer\psparser.py", line 172, in __init__
    self.seek(0)

AttributeError: 'PDFParser' object has no attribute 'seek'
```

- document` = PDFDocument(parser)

```
Traceback (most recent call last):
  File "<ipython-input-604-2cf71ad19102>", line 1, in <module>
    document = PDFDocument(parser)
  File "D:\anaconda3\lib\site-packages\pdfminer\pdfdocument.py", line 571, in __init__
    pos = self.find_xref(parser)
  File "D:\anaconda3\lib\site-packages\pdfminer\pdfdocument.py", line 788, in find_xref
    for line in parser.revreadlines():
AttributeError: 'PDFParser' object has no attribute 'revreadlines'
```

**Comment by pietermarsman** [comment]
Hi @Ocruc28, can you share the PDF you are using that generates this error?

**Comment by pietermarsman** [comment]
@Ocruc28 this is a friendly reminder to share some extra details.

**Comment by booleank** [comment]
Did you happen to figure this out?
