### ISSUE TITLE
🐛 TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by astariul** [pdfminer/pdfminer.six#541]
## File 

[aa.pdf](https://github.com/pdfminer/pdfminer.six/files/5456749/aa.pdf)

## Description

When trying to extract the pages from this file, I'm having following error :

> File "/home/remondn/.venv/stable_prospector/lib/python3.6/site-packages/pdfminer/encodingdb.py", line 27, in name2unicode
    name = name.split('.')[0]
TypeError: a bytes-like object is required, not 'str'

## Code

```python
from pdfminer.high_level import extract_pages
list(extract_pages("aa.pdf"))
```

## Full stack-trace

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/remondn/.venv/stable_prospector/lib/python3.6/site-packages/pdfminer/high_level.py", line 149, in extract_pages
    interpreter.process_page(page)
  File "/home/remondn/.venv/stable_prospector/lib/python3.6/site-packages/pdfminer/pdfinterp.py", line 895, in process_page
    self.render_contents(page.resources, page.contents, ctm=ctm)
  File "/home/remondn/.venv/stable_prospector/lib/python3.6/site-packages/pdfminer/pdfinterp.py", line 908, in render_contents
    self.execute(list_value(streams))
  File "/home/remondn/.venv/stable_prospector/lib/python3.6/site-packages/pdfminer/pdfinterp.py", line 933, in execute
    func(*args)
  File "/home/remondn/.venv/stable_prospector/lib/python3.6/site-packages/pdfminer/pdfinterp.py", line 872, in do_Do
    ctm=mult_matrix(matrix, self.ctm))
  File "/home/remondn/.venv/stable_prospector/lib/python3.6/site-packages/pdfminer/pdfinterp.py", line 906, in render_contents
    self.init_resources(resources)
  File "/home/remondn/.venv/stable_prospector/lib/python3.6/site-packages/pdfminer/pdfinterp.py", line 354, in init_resources
    self.fontmap[fontid] = self.rsrcmgr.get_font(objid, spec)
  File "/home/remondn/.venv/stable_prospector/lib/python3.6/site-packages/pdfminer/pdfinterp.py", line 190, in get_font
    font = PDFType3Font(self, spec)
  File "/home/remondn/.venv/stable_prospector/lib/python3.6/site-packages/pdfminer/pdffont.py", line 647, in __init__
    PDFSimpleFont.__init__(self, descriptor, widths, spec)
  File "/home/remondn/.venv/stable_prospector/lib/python3.6/site-packages/pdfminer/pdffont.py", line 575, in __init__
    self.cid2unicode = EncodingDB.get_encoding(name, diff)
  File "/home/remondn/.venv/stable_prospector/lib/python3.6/site-packages/pdfminer/encodingdb.py", line 108, in get_encoding
    cid2unicode[cid] = name2unicode(x.name)
  File "/home/remondn/.venv/stable_prospector/lib/python3.6/site-packages/pdfminer/encodingdb.py", line 27, in name2unicode
    name = name.split('.')[0]
TypeError: a bytes-like object is required, not 'str'
```

## Environment
- OS : Ubuntu 18.04.4 LTS (Bionic Beaver)
- Python version : 3.6.9
- `pdfminer` version : 20200726

---

**How can I run `extract_pages()` without having this error ?**

**Comment by pietermarsman** [comment]
Hi @astariul-colanim,

Thanks for raising the issue. I can replicate it with `python tools/pdf2txt.py ~/Downloads/aa.pdf`. This should not happen. 

Its related to these issues:
- https://github.com/pdfminer/pdfminer.six/issues/423
- https://github.com/pdfminer/pdfminer.six/issues/277

(I prefer to keep them all open because we need to make sure the issue is fixed for each of the input pdf's)

**Comment by astariul-colanim** [comment]
Thanks @pietermarsman 

Can you give me a pointer where can I monkey-patch the library to make it work ? (just a work-around is fine for me)

**Comment by manjoc** [comment]
not suitable solution:

at `pdfminer/encodingdb.py`, judge the type of `name`

```python
def name2unicode(name):
    """Converts Adobe glyph names to Unicode numbers.

    In contrast to the specification, this raises a KeyError instead of return
    an empty string when the key is unknown.
    This way the caller must explicitly define what to do
    when there is not a match.

    Reference:
    https://github.com/adobe-type-tools/agl-specification#2-the-mapping

    :returns unicode character if name resembles something,
    otherwise a KeyError
    """
    if isinstance(name, str):
        name = name
    else:
        name = name.decode('utf-8')
    name = name.split('.')[0]
    components = name.split('_')
```
