### ISSUE TITLE
PSEOF: Unexpected EOF when ATTACHMENTS are present in a pdf

### ISSUE THREAD

**Issue by swarup008** [pdfminer/pdfminer.six#545]
This problem occurs when there are **ATTACHMENTS** present within a pdf file.

I have provided a sample file in the below link:
[attachment_test.pdf](https://github.com/pdfminer/pdfminer.six/files/5507157/attachment_test.pdf)

Screenshot of an example file:
![image](https://user-images.githubusercontent.com/35597446/98484003-816c4e00-2232-11eb-9221-fb8ff64e76a2.png)

_Originally posted by @swarup008 in https://github.com/pdfminer/pdfminer.six/issues/448#issuecomment-723664379_

**Comment by pietermarsman** [comment]
I get this error when running `python tools/pdf2txt.py ~/Downloads/attachment_test.pdf`. Is that the problem you're experiencing? 

```
Traceback (most recent call last):
  File "tools/pdf2txt.py", line 204, in <module>
    sys.exit(main())
  File "tools/pdf2txt.py", line 198, in main
    outfp = extract_text(**vars(A))
  File "tools/pdf2txt.py", line 66, in extract_text
    pdfminer.high_level.extract_text_to_fp(fp, **locals())
  File "/home/pieter/projects/pdfminer/pdfminer-upstream/pdfminer/high_level.py", line 83, in extract_text_to_fp
    caching=not disable_caching):
  File "/home/pieter/projects/pdfminer/pdfminer-upstream/pdfminer/pdfpage.py", line 128, in get_pages
    doc = PDFDocument(parser, password=password, caching=caching)
  File "/home/pieter/projects/pdfminer/pdfminer-upstream/pdfminer/pdfdocument.py", line 578, in __init__
    xref.load(parser)
  File "/home/pieter/projects/pdfminer/pdfminer-upstream/pdfminer/pdfdocument.py", line 190, in load
    (_, obj) = parser.nextobject()
  File "/home/pieter/projects/pdfminer/pdfminer-upstream/pdfminer/psparser.py", line 567, in nextobject
    (pos, token) = self.nexttoken()
  File "/home/pieter/projects/pdfminer/pdfminer-upstream/pdfminer/psparser.py", line 493, in nexttoken
    self.fillbuf()
  File "/home/pieter/projects/pdfminer/pdfminer-upstream/pdfminer/psparser.py", line 221, in fillbuf
    raise PSEOF('Unexpected EOF')
pdfminer.psparser.PSEOF: Unexpected EOF
```

**Comment by SWARUP-Selvaraj** [comment]
Exactly.  When PDF file has got attachments, PDF Miner throws unexpected EOF error.

**Comment by AlexanderMoan** [comment]
Has this issue been resolved?

**Comment by pietermarsman** [comment]
Nope. Feel free to open a PR.

**Comment by shwetabhsharan** [comment]
Do we have a way to remove the attachments before processing the pages using PDFMiner?

**Comment by pietermarsman** [comment]
@shwetabhsharan Not by using pdfminer.six. Perhaps another tool can do it for you.

**Comment by shwetabhsharan** [comment]
@pietermarsman Thanks for responding. Cheers.

**Comment by ageitgey** [comment]
Hi, we ran into this bug and then tracked it down. I don't think it's really a bug in `pdfminer.six` - at least it wasn't for us.

How to reproduce:
1. Upload the test pdf file from this thread to an S3 bucket
1. Download the pdf file from S3 using the `boto3.download_fileobj()` function.
1. Try to parse the pdf file with `pdfminer.six` - Result: `pdfminer.psparser.PSEOF: Unexpected EOF`

How to fix:
1. Replace the call to `boto3.download_fileobj()` with `boto3.download_file()` (and use a temporary file name instead of a file handle to write into)

Explanation:

When you download a pdf file with an attachment using `boto3.download_fileobj()`, it truncates the attachment in the pdf file. You can validate this by downloading the file from s3 using `boto3.download_fileobj()`:

```
# a.pdf - your original file
# b.pdf - the copy you downloaded from S3 using boto3.downloadfileobj()

# Convert both files to hex format
xxd a.pdf > a.hex
xxd b.pdf > b.hex

# Diff the hex versions
diff a.hex b.hex
```

Result: The download copy is missing the attachment block at the end of the PDF file:

```
< 00040000: 2020 2020 2020 2020 0a20 2020 2020 2020          .
< 00040010: 2020 2020 2020 2020 2020 2020 2020 2020
< 00040020: 2020 2020 0a3c 3f78 7061 636b 6574 2065      .<?xpacket e
< 00040030: 6e64 3d22 7722 3f3e 0a65 6e64 7374 7265  nd="w"?>.endstre
< 00040040: 616d 0a65 6e64 6f62 6a0a 3333 2030 206f  am.endobj.33 0 o
< 00040050: 626a 0a3c 3c2f 4669 6c74 6572 2f46 6c61  bj.<</Filter/Fla
< 00040060: 7465 4465 636f 6465 2f46 6972 7374 2032  teDecode/First 2
< 00040070: 312f 4c65 6e67 7468 2031 3130 2f4e 2033  1/Length 110/N 3
< 00040080: 2f54 7970 652f 4f62 6a53 746d 3e3e 7374  /Type/ObjStm>>st
[ .. etc ..]
```

So of course pdfminer can't parse it - the file is broken. But it appears that it is `boto3.download_fileobj()` that broke the file. The copy in S3 is fine.

**Comment by dhdaines** [comment]
Appears to be fixed now, or at least it doesn't crash.
