### ISSUE TITLE
Unexpected KeyError on malformed PDF

### ISSUE THREAD

**Issue by Google-Autofuzz** [pdfminer/pdfminer.six#551]
When running the following code with the latest pypi version of pdfminer.six on the attached input results in an unexpected `KeyError`:

```python
import io
import sys

from pdfminer import high_level

with open(sys.argv[1], 'rb') as f:
    high_level.extract_text_to_fp(f, io.BytesIO())
```

```python
$ python3 pdfminer_repro.py ../test.pdf 
Traceback (most recent call last):
  File "pdfminer_repro.py", line 7, in <module>
    high_level.extract_text_to_fp(f, io.BytesIO())
  File "/home/user/.local/lib/python3.8/site-packages/pdfminer/high_level.py", line 79, in extract_text_to_fp
    for page in PDFPage.get_pages(inf,
  File "/home/user/.local/lib/python3.8/site-packages/pdfminer/pdfpage.py", line 142, in get_pages
    for (pageno, page) in enumerate(cls.create_pages(doc)):
  File "/home/user/.local/lib/python3.8/site-packages/pdfminer/pdfpage.py", line 116, in create_pages
    yield cls(document, objid, obj)
  File "/home/user/.local/lib/python3.8/site-packages/pdfminer/pdfpage.py", line 55, in __init__
    self.mediabox = resolve1(self.attrs['MediaBox'])
KeyError: 'MediaBox'
$ 
```
[test.pdf](https://github.com/pdfminer/pdfminer.six/files/5537234/test.pdf)

**Comment by pietermarsman** [comment]
Hi @Google-Autofuzz,

Raising an error in case of a (unsupported) malformed pdf is the expected behavior for pdfminer.six.

Let me know if you disagree in this instance.
