### ISSUE TITLE
Unexpected KeyError on malformed PDF

### ISSUE THREAD

**Issue by Google-Autofuzz** [pdfminer/pdfminer.six#553]
When running the following code with the latest pypi version of pdfminer.six on the attached input results in an unexpected `KeyError`:

```python
import io
import sys

from pdfminer import high_level

with open(sys.argv[1], 'rb') as f:
    high_level.extract_text_to_fp(f, io.BytesIO())
```

```python
$ python3 pdfminer_repro.py ../test.pdf 
Traceback (most recent call last):
  File "pdfminer_repro.py", line 7, in <module>
    high_level.extract_text_to_fp(f, io.BytesIO())
  File "/home/user/.local/lib/python3.8/site-packages/pdfminer/high_level.py", line 79, in extract_text_to_fp
    for page in PDFPage.get_pages(inf,
  File "/home/user/.local/lib/python3.8/site-packages/pdfminer/pdfpage.py", line 128, in get_pages
    doc = PDFDocument(parser, password=password, caching=caching)
  File "/home/user/.local/lib/python3.8/site-packages/pdfminer/pdfdocument.py", line 588, in __init__
    self._initialize_password(password)
  File "/home/user/.local/lib/python3.8/site-packages/pdfminer/pdfdocument.py", line 614, in _initialize_password
    handler = factory(docid, param, password)
  File "/home/user/.local/lib/python3.8/site-packages/pdfminer/pdfdocument.py", line 296, in __init__
    self.init()
  File "/home/user/.local/lib/python3.8/site-packages/pdfminer/pdfdocument.py", line 300, in init
    self.init_params()
  File "/home/user/.local/lib/python3.8/site-packages/pdfminer/pdfdocument.py", line 312, in init_params
    self.u = str_value(self.param['U'])
KeyError: 'U'
$ 
```
[test.pdf](https://github.com/pdfminer/pdfminer.six/files/5546035/test.pdf)

**Comment by pietermarsman** [comment]
Hi @Google-Autofuzz,

Raising an error in case of a (unsupported) malformed pdf is the expected behavior for pdfminer.six.

Let me know if you disagree in this instance.

**Comment by Google-Autofuzz** [comment]
I would expect an exception inherited from `PDFException` instead of a `KeyError`, otherwise, users have to catch all possible exceptions when using pdfminer.six, which is a bit ugly.

It would be nice to [document]( https://pdfminersix.readthedocs.io/en/latest/reference/highlevel.html#extract-text-to-fp ) that pdfminer.six can raise any kind og exception, because it's not clear at the moment.
