### ISSUE TITLE
KeyError: 'Type'  (in stream when opening some pdf)

### ISSUE THREAD

**Issue by BaptCha** [pdfminer/pdfminer.six#559]
**Bug report**
Environment:
macOS11.0.1 (20B50)--Python 3.8.1 + pdfminer.six==20200517

======code============
```python
import requests
from pdfminer.pdfparser import PDFParser
from pdfminer.pdfdocument import PDFDocument
from io import BytesIO

# not working sample
url = "https://www.ema.europa.eu/en/documents/product-information/cerdelga-epar-product-information_fr.pdf"

# working sample
#url = "https://www.ema.europa.eu/en/documents/product-information/xeplion-epar-product-information_fr.pdf" 

content = requests.get(url).content

pdf = PDFDocument(PDFParser(BytesIO(content)))
```
============ error stacktrace===================

```
KeyError                                  Traceback (most recent call last)
<ipython-input-11-6e35d3400db4> in <module>
----> 1 pdf = PDFDocument(PDFParser(BytesIO(content)))

//Users/baptiste/.pyenv/versions/3.8.1/lib/python3.8/site-packages/pdfminer/pdfdocument.py in __init__(self, parser, password, caching, fallback)
    546         try:
    547             pos = self.find_xref(parser)
--> 548             self.read_xref_from(parser, pos, self.xrefs)
    549         except PDFNoValidXRef:
    550             pass  # fallback = True

//Users/baptiste/.pyenv/versions/3.8.1/lib/python3.8/site-packages/pdfminer/pdfdocument.py in read_xref_from(self, parser, start, xrefs)
    788             parser.reset()
    789             xref = PDFXRefStream()
--> 790             xref.load(parser)
    791         else:
    792             if token is parser.KEYWORD_XREF:

//Users/baptiste/.pyenv/versions/3.8.1/lib/python3.8/site-packages/pdfminer/pdfdocument.py in load(self, parser)
    219         (_, kwd) = parser.nexttoken()
    220         (_, stream) = parser.nextobject()
--> 221         if not isinstance(stream, PDFStream) or stream["Type"] is not LITERAL_XREF:
    222             raise PDFNoValidXRef("Invalid PDF stream spec.")
    223         size = stream["Size"]

//Users/baptiste/.pyenv/versions/3.8.1/lib/python3.8/site-packages/pdfminer/pdftypes.py in __getitem__(self, name)
    217 
    218     def __getitem__(self, name):
--> 219         return self.attrs[name]
    220 
    221     def get(self, name, default=None):

KeyError: 'Type'
```

**Comment by pietermarsman** [comment]
I can replicate this.

**Comment by lroberts7** [comment]
I am also seeing this while parsing a pdf via camelot, stacktrace:
```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/opt/homebrew/lib/python3.11/site-packages/camelot/io.py", line 113, in read_pdf
    tables = p.parse(
             ^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/camelot/handlers.py", line 169, in parse
    self._save_page(self.filepath, p, tempdir)
  File "/opt/homebrew/lib/python3.11/site-packages/camelot/handlers.py", line 118, in _save_page
    layout, dim = get_page_layout(fpath)
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/camelot/utils.py", line 893, in get_page_layout
    interpreter.process_page(page)
  File "/opt/homebrew/lib/python3.11/site-packages/pdfminer/pdfinterp.py", line 997, in process_page
    self.render_contents(page.resources, page.contents, ctm=ctm)
  File "/opt/homebrew/lib/python3.11/site-packages/pdfminer/pdfinterp.py", line 1014, in render_contents
    self.init_resources(resources)
  File "/opt/homebrew/lib/python3.11/site-packages/pdfminer/pdfinterp.py", line 387, in init_resources
    colorspace = get_colorspace(resolve1(spec))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pdfminer/pdfinterp.py", line 370, in get_colorspace
    return PDFColorSpace(name, stream_value(spec[1])["N"])
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pdfminer/pdftypes.py", line 285, in __getitem__
    return self.attrs[name]
           ~~~~~~~~~~^^^^^^
KeyError: 'N'
```
@pietermarsman given that `self.attrs` is a dictionary, would it make sense to do the usual thing here? 

e.g. do:
```
return self.attrs.get(name)
```
it will return `None` if the `name` key isn't present, or add a (custom) default as the second argument to `.get()`

**Comment by lroberts7** [comment]
Answering my query, that won't fix the issue I'm seeing:
```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/opt/homebrew/lib/python3.11/site-packages/camelot/io.py", line 113, in read_pdf
    tables = p.parse(
             ^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/camelot/handlers.py", line 169, in parse
    self._save_page(self.filepath, p, tempdir)
  File "/opt/homebrew/lib/python3.11/site-packages/camelot/handlers.py", line 118, in _save_page
    layout, dim = get_page_layout(fpath)
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/camelot/utils.py", line 893, in get_page_layout
    interpreter.process_page(page)
  File "/opt/homebrew/lib/python3.11/site-packages/pdfminer/pdfinterp.py", line 997, in process_page
    self.render_contents(page.resources, page.contents, ctm=ctm)
  File "/opt/homebrew/lib/python3.11/site-packages/pdfminer/pdfinterp.py", line 1016, in render_contents
    self.execute(list_value(streams))
  File "/opt/homebrew/lib/python3.11/site-packages/pdfminer/pdfinterp.py", line 1045, in execute
    func()
  File "/opt/homebrew/lib/python3.11/site-packages/pdfminer/pdfinterp.py", line 717, in do_scn
    self.graphicstate.ncolor = cast(Color, self.pop(n))
                                           ^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pdfminer/pdfinterp.py", line 422, in pop
    x = self.argstack[-n:]
                      ^^
TypeError: bad operand type for unary -: 'NoneType'
>>> 
```

**Comment by lroberts7** [comment]
I looked a little closer it seems that the issue is (unsurprisingly the "N" key/val pair are missing from the `stream_value(spec[1])` call. In my case I'm seeing instances both with and without the `'N'` key in the dictionary. 
In the cases where the `'N'` key is not prevalent, there is still the alternate/color space key/val pair which could maybe be used to infer the 'N' value? On my examples I see:

```
{'Alternate': /'DeviceRGB', 'Filter': /'FlateDecode', 'N': 3, 'Length': 2598}
```
and 
```
{'Alternate': /'DeviceCMYK', 'Filter': /'FlateDecode', 'N': 4, 'Length': 389758}
```
so it would seem like the presence of RGB could set `'N'` to 3 by default, and CMYk could set 4 to default etc. 

However, I'm not sure if there ***should*** be an `'N'` value in these cases and it's not getting parsed or if this is an issue in the pdf setup itself.
