### ISSUE TITLE
Missing parsing of cross reference streams?

### ISSUE THREAD

**Issue by TiDreyer** [pdfminer/pdfminer.six#581]
**Bug report**

I'm not sure, if this is more of a bug report or a feature request...

I'm trying to parse a pdf file, but I get the following error (similar to #476):

```
Traceback (most recent call last):
  File "G:/git/ids/ids_lib/reader/pdf_reader.py", line 135, in <module>
    reader.open(pdf_path)
  File "G:/git/ids/ids_lib/reader/pdf_reader.py", line 56, in open
    self._first_page = next(extract_pages(file_object))
  File "G:\git\ids\venv\lib\site-packages\pdfminer\high_level.py", line 147, in extract_pages
    for page in PDFPage.get_pages(fp, page_numbers, maxpages=maxpages,
  File "G:\git\ids\venv\lib\site-packages\pdfminer\pdfpage.py", line 128, in get_pages
    doc = PDFDocument(parser, password=password, caching=caching)
  File "G:\git\ids\venv\lib\site-packages\pdfminer\pdfdocument.py", line 596, in __init__
    raise PDFSyntaxError('No /Root object! - Is this really a PDF?')
pdfminer.pdfparser.PDFSyntaxError: No /Root object! - Is this really a PDF?
```

This happens for PDF files created with a special program, which are all confidential, so unfortunately I can't attach them here. However, the program seems to use the `PDF Xpansion 12.0.3.1` library to create the files. This is part of one PDF's plain text:

```
%PDF-1.7
%òÄàÓ

2 0 obj
<</Pages 3 0 R/Type/Catalog/Version/1.7>>
endobj

-- content --

17 0 obj
<</Filter/FlateDecode/ID[<FB277E7F178578439E730C03327E95DC><FB277E7F178578439E730C03327E95DC>]/Index[0 17]/Info 1 0 R/Length 56/Root 2 0 R/Size 17/Type/XRef/W[1 2 1]>>stream

-- two lines of binary --

endstream
endobj
startxref 10981
%%EOF
```

From how I understand section 7.5.8 of the [PDF 1.7 specification](https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf), this pdf ends with a cross reference stream, as opposed to a cross reference table (section 7.5.4). Without having a real understanding of the pdf standard, this looks valid to me.

The exception that I get is raised in [this line](https://github.com/pdfminer/pdfminer.six/blob/178a831802191f2b687a390bd12b794a48ad7fd9/pdfminer/pdfdocument.py#L596). Judging from the code before that, it seems like `pdfminer.six` is not capable (yet) of parsing PDFs that use cross reference streams instead of tables?

**Comment by TiDreyer** [comment]
I'd be really grateful just to know, if this is a missing feature in `pdfminer.six` or a bug in the software creating the PDF files.

**Comment by TiDreyer** [comment]
It appears that the value after `startref` needs to be on a separate line, as indicated by this helpful warning by `PyPDF2`:

```
>>> import PyPDF2 as pdf
>>> my_pdf = pdf.PdfFileReader(pdf_file_path)
UserWarning: startxref on same line as offset [pdf.py:1709]
```

And indeed, after manually changing the last lines to the following using vim, the error from `pdfminer.six` disappears.

```
endobj
startxref
10981
%%EOF
```

That is, the error seems to be in the PDF file, not in the package. Feel free to close this issue, but maybe consider if it is possible to give a better error message or even allow the reading of these small errors in PDF syntax.

**Comment by TiDreyer** [comment]
Closing this issue, since it's a problem in the PDF files used.

For possible people with a similar problem in the future:
Our software department confirms that this is a bug in the libary `PDF Xpansion` (and therefore won't be fixed soon). I'm now manually fixing the PDFs before parsing them:

```python
def fix_common_pdf_errors_inplace(pdf_file_path):
    with open(pdf_file_path, "rb") as original, open(pdf_file_path+"_fixed", "wb") as fixed:
        for line in original:
            if line.startswith(b"startxref "):
                # replace the space after 'startxref' with a newline
                line_str = line.decode()
                keyword, address = line_str.strip().split()
                line_mod = f"{keyword}\n{address}\n".encode()
                fixed.write(line_mod)
            else:
                fixed.write(line)
```
