### ISSUE TITLE
pdf2txt gives TypeError: 'float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by evanmiltenburg** [pdfminer/pdfminer.six#629]
The `pdf2txt` tool crashes when I try to convert [this pdf](https://www.aclweb.org/anthology/2021.naacl-main.176.pdf) to text. Traceback below.

```
Traceback (most recent call last):
  File "get_text.py", line 9, in <module>
    outfp = extract_text(files=[pdf], 
  File "/Users/emiel/Tilburg/Projects/Ethical considerations/tools/pdf2txt.py", line 66, in extract_text
    pdfminer.high_level.extract_text_to_fp(fp, **locals())
  File "/Users/emiel/miniconda3/lib/python3.8/site-packages/pdfminer/high_level.py", line 85, in extract_text_to_fp
    interpreter.process_page(page)
  File "/Users/emiel/miniconda3/lib/python3.8/site-packages/pdfminer/pdfinterp.py", line 895, in process_page
    self.render_contents(page.resources, page.contents, ctm=ctm)
  File "/Users/emiel/miniconda3/lib/python3.8/site-packages/pdfminer/pdfinterp.py", line 908, in render_contents
    self.execute(list_value(streams))
  File "/Users/emiel/miniconda3/lib/python3.8/site-packages/pdfminer/pdfinterp.py", line 933, in execute
    func(*args)
  File "/Users/emiel/miniconda3/lib/python3.8/site-packages/pdfminer/pdfinterp.py", line 871, in do_Do
    interpreter.render_contents(resources, [xobj],
  File "/Users/emiel/miniconda3/lib/python3.8/site-packages/pdfminer/pdfinterp.py", line 908, in render_contents
    self.execute(list_value(streams))
  File "/Users/emiel/miniconda3/lib/python3.8/site-packages/pdfminer/pdfinterp.py", line 933, in execute
    func(*args)
  File "/Users/emiel/miniconda3/lib/python3.8/site-packages/pdfminer/pdfinterp.py", line 871, in do_Do
    interpreter.render_contents(resources, [xobj],
  File "/Users/emiel/miniconda3/lib/python3.8/site-packages/pdfminer/pdfinterp.py", line 906, in render_contents
    self.init_resources(resources)
  File "/Users/emiel/miniconda3/lib/python3.8/site-packages/pdfminer/pdfinterp.py", line 354, in init_resources
    self.fontmap[fontid] = self.rsrcmgr.get_font(objid, spec)
  File "/Users/emiel/miniconda3/lib/python3.8/site-packages/pdfminer/pdfinterp.py", line 202, in get_font
    font = self.get_font(None, subspec)
  File "/Users/emiel/miniconda3/lib/python3.8/site-packages/pdfminer/pdfinterp.py", line 193, in get_font
    font = PDFCIDFont(self, spec)
  File "/Users/emiel/miniconda3/lib/python3.8/site-packages/pdfminer/pdffont.py", line 717, in __init__
    widths = get_widths(list_value(spec.get('W', [])))
  File "/Users/emiel/miniconda3/lib/python3.8/site-packages/pdfminer/pdffont.py", line 50, in get_widths
    for i in range(char1, char2+1):
TypeError: 'float' object cannot be interpreted as an integer
```

**Comment by pietermarsman** [comment]
Can still reproduce with

```
$ .venv/bin/python tools/pdf2txt.py ~/Downloads/2021.naacl-main.176.pdf -p 3
[...]
  File "/home/pieter/projects/pdfminer.six/pdfminer/pdfinterp.py", line 990, in render_contents
    self.init_resources(resources)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/home/pieter/projects/pdfminer.six/pdfminer/pdfinterp.py", line 403, in init_resources
    self.fontmap[fontid] = self.rsrcmgr.get_font(objid, spec)
                           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/pieter/projects/pdfminer.six/pdfminer/pdfinterp.py", line 241, in get_font
    font = self.get_font(None, subspec)
  File "/home/pieter/projects/pdfminer.six/pdfminer/pdfinterp.py", line 232, in get_font
    font = PDFCIDFont(self, spec)
  File "/home/pieter/projects/pdfminer.six/pdfminer/pdffont.py", line 1134, in __init__
    widths = get_widths(list_value(spec.get("W", [])))
  File "/home/pieter/projects/pdfminer.six/pdfminer/pdffont.py", line 75, in get_widths
    for i in range(cast(int, char1), cast(int, char2) + 1):
             ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'float' object cannot be interpreted as an integer
```
