### ISSUE TITLE
AssertionError during layout analysis

### ISSUE THREAD

**Issue by hughsw** [pdfminer/pdfminer.six#66]
I am using the excellent pdfminer.six package for analysis of text in PDFs that my clients receive from their clients.  

I hit an assert failure while using the `PDFPageAggregator` converter.  Here are the code, PDF, and stack trace:

https://github.com/hughsw/pdfminer.six/blob/master/tools/pdfstats.py

[arm_ed_t_board_elektor_magazine_article.pdf](https://github.com/pdfminer/pdfminer.six/files/1030116/arm_ed_t_board_elektor_magazine_article.pdf)

```pdfstats.py ['/Users/hugh/Downloads/arm_ed_t_board_elektor_magazine_article.pdf']
Traceback (most recent call last):
  File "./pdfstats.py", line 81, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./pdfstats.py", line 71, in main
    interpreter.process_page(page)
  File "/usr/local/lib/python3.6/site-packages/pdfminer/pdfinterp.py", line 851, in process_page
    self.device.end_page(page)
  File "/usr/local/lib/python3.6/site-packages/pdfminer/converter.py", line 51, in end_page
    self.cur_item.analyze(self.laparams)
  File "/usr/local/lib/python3.6/site-packages/pdfminer/layout.py", line 677, in analyze
    obj.analyze(laparams)
  File "/usr/local/lib/python3.6/site-packages/pdfminer/layout.py", line 724, in analyze
    LTLayoutContainer.analyze(self, laparams)
  File "/usr/local/lib/python3.6/site-packages/pdfminer/layout.py", line 684, in analyze
    textboxes = list(self.group_textlines(laparams, textlines))
  File "/usr/local/lib/python3.6/site-packages/pdfminer/layout.py", line 579, in group_textlines
    neighbors = line.find_neighbors(plane, laparams.line_margin)
  File "/usr/local/lib/python3.6/site-packages/pdfminer/layout.py", line 387, in find_neighbors
    return [obj for obj in objs
  File "/usr/local/lib/python3.6/site-packages/pdfminer/layout.py", line 387, in <listcomp>
    return [obj for obj in objs
  File "/usr/local/lib/python3.6/site-packages/pdfminer/utils.py", line 373, in find
    for k in self._getrange(bbox):
  File "/usr/local/lib/python3.6/site-packages/pdfminer/utils.py", line 335, in _getrange
    for y in drange(y0, y1, self.gridsize):
  File "/usr/local/lib/python3.6/site-packages/pdfminer/utils.py", line 173, in drange
    assert v0 < v1
AssertionError: (807.874, 807.874, 50)
```

**Comment by pietermarsman** [comment]
Fixed by #246
