### ISSUE TITLE
extract_text does not accept file-like object despite manual explicitly states so

### ISSUE THREAD

**Issue by hholst80** [pdfminer/pdfminer.six#692]
Per documentation: https://pdfminersix.readthedocs.io/en/latest/reference/highlevel.html#api-extract-text
```
extract_text
pdfminer.high_level.extract_text(pdf_file, password='', page_numbers=None, maxpages=0, caching=True, codec='utf-8', laparams=None)
Parse and return the text contained in a PDF file.

Parameters:	
pdf_file – Either a file path or a file-like object for the PDF file to be worked on.
```

https://stackoverflow.com/questions/4359495/what-is-exactly-a-file-like-object-in-python

What it *actually* requires is a path; a str; or a bytes object.

But sending in a `bytes` object will not work either because it will interpret the data as a file path object.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/om/Documents/GitHub/centsoft/pdf-to-text/app.py", line 15, in pdf_to_text
    text = extract_text(data)
  File "/usr/local/lib/python3.8/dist-packages/pdfminer/high_level.py", line 120, in extract_text
    with open(pdf_file, "rb") as fp, StringIO() as output_string:
TypeError: expected str, bytes or os.PathLike object, not _io.BytesIO
```

**Comment by pietermarsman** [comment]
A `bytes` object is not a file. According to the SO post, file-like objects have a `read()` and a `write()` method. 

But `bytes` has not:

```
>>> bytes.read
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'str' has no attribute 'read'
>>> bytes.write
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'str' has no attribute 'write'

```

Try using [`io.BytesIO`](https://docs.python.org/3/library/io.html#io.BytesIO) instead.

**Comment by hholst80** [comment]
I feel a bit confused reading this myself now. Obviously I know that bytes objects are not file-like objects so there must have been some other point I was implicitly trying to make but I cannot remember what now. Sorry for being imprecise. I'll look into this at a later point. Thank you for your help.
