### ISSUE TITLE
Buggy as hell

### ISSUE THREAD

**Issue by rgosens2** [pdfminer/pdfminer.six#694]
```
% pdf2txt.py vol2a.pdf  
Traceback (most recent call last):
  File "/usr/local/bin/pdf2txt.py", line 224, in <module>
    sys.exit(main())
  File "/usr/local/bin/pdf2txt.py", line 218, in main
    outfp = extract_text(**vars(A))
  File "/usr/local/bin/pdf2txt.py", line 86, in extract_text
    pdfminer.high_level.extract_text_to_fp(fp, **locals())
  File "/usr/local/lib/python3.9/site-packages/pdfminer/high_level.py", line 103, in extract_text_to_fp
    for page in PDFPage.get_pages(inf,
  File "/usr/local/lib/python3.9/site-packages/pdfminer/pdfpage.py", line 147, in get_pages
    doc = PDFDocument(parser, password=password, caching=caching)
  File "/usr/local/lib/python3.9/site-packages/pdfminer/pdfdocument.py", line 694, in __init__
    pos = self.find_xref(parser)
  File "/usr/local/lib/python3.9/site-packages/pdfminer/pdfdocument.py", line 935, in find_xref
    for line in parser.revreadlines():
  File "/usr/local/lib/python3.9/site-packages/pdfminer/psparser.py", line 283, in revreadlines
    n = max(s.rfind('\r'), s.rfind('\n'))
TypeError: argument should be integer or bytes-like object, not 'str'
```

**Comment by rgosens2** [comment]
OK works after uninstall and install.
