### ISSUE TITLE
pdfminer.six haven't included error handling for the response from the url

### ISSUE THREAD

**Issue by yiqifengba** [pdfminer/pdfminer.six#792]
When using urlopen("http://pythonscraping.com/pages/warandpeace/chapter1.pdf") as fp (param of PDFParser),
raise     io.UnsupportedOperation: seek

Details:
Traceback (most recent call last):

  File "/usr/local/lib/python3.6/dist-packages/pdfminer/pdfparser.py", line 42, in __init__
    PSStackParser.__init__(self, fp)
  File "/usr/local/lib/python3.6/dist-packages/pdfminer/psparser.py", line 543, in __init__
    PSBaseParser.__init__(self, fp)
  File "/usr/local/lib/python3.6/dist-packages/pdfminer/psparser.py", line 193, in __init__
    self.seek(0)
  File "/usr/local/lib/python3.6/dist-packages/pdfminer/psparser.py", line 555, in seek
    PSBaseParser.seek(self, pos)
  File "/usr/local/lib/python3.6/dist-packages/pdfminer/psparser.py", line 220, in seek
    self.fp.seek(pos)
io.UnsupportedOperation: seek

**Comment by KunalGehlot** [comment]
Are you using the `read()` method on `fp`?

Refer [this SO question](https://stackoverflow.com/questions/25863101/python-urllib-urlopen-not-working)

**Comment by yiqifengba** [comment]
I used urlopen() method on fp

**Comment by yiqifengba** [comment]
When I use open() method on my local pdf file, PDFParser(fp) works fine.

**Comment by KunalGehlot** [comment]
Did you visit the SO Question I linked?

What you need to do is this:
```python3
with urlopen("http://pythonscraping.com/pages/warandpeace/chapter1.pdf") as fp:
    file = fp.read()
```

**Comment by yiqifengba** [comment]
'bytes' object has no attribute 'seek'
Details:
Traceback (most recent call last):
  File "/root/Code/python-scraping/v1/chapter6/test5.py", line 61, in <module>
    outputString = readPDF(pdfFile)
  File "/root/Code/python-scraping/v1/chapter6/test5.py", line 38, in readPDF
    parser = PDFParser(pdfFile)
  File "/usr/local/lib/python3.6/dist-packages/pdfminer/pdfparser.py", line 42, in __init__
    PSStackParser.__init__(self, fp)
  File "/usr/local/lib/python3.6/dist-packages/pdfminer/psparser.py", line 543, in __init__
    PSBaseParser.__init__(self, fp)
  File "/usr/local/lib/python3.6/dist-packages/pdfminer/psparser.py", line 193, in __init__
    self.seek(0)
  File "/usr/local/lib/python3.6/dist-packages/pdfminer/psparser.py", line 555, in seek
    PSBaseParser.seek(self, pos)
  File "/usr/local/lib/python3.6/dist-packages/pdfminer/psparser.py", line 220, in seek
    self.fp.seek(pos)
AttributeError: 'bytes' object has no attribute 'seek'

**Comment by pietermarsman** [comment]
Not an issue with pdfminer.six. 

You need to pass an file-like object to pdfminer, the [output of urlopen](https://docs.python.org/3/library/urllib.request.html#urllib.request.urlopen) is not.
