### ISSUE TITLE
No module named 'pdfminer.converter'

### ISSUE THREAD

**Issue by chrdlz** [pdfminer/pdfminer.six#835]
I have an issue when I am importing pdfminer in my python code:

```
Traceback (most recent call last):
  File "/Users/.../SB_analyser_main.py", line 14, in <module>
    from pdfminer.high_level import extract_text, extract_text_to_fp
  File "/Users/.../Library/Python/3.9/lib/python/site-packages/pdfminer/high_level.py", line 8, in <module>
    from .converter import (
ModuleNotFoundError: No module named 'pdfminer.converter'
```

The same code worked just fine the last time I used it, in June 2022.

**Comment by KunalGehlot** [comment]
Please make sure that you do not have conflicting libraries in your system. Try re-installing pdfminer.six and if it still doesn't work, try importing the functions via

```python
import pdfminer
from pdfminer.converter import TextConverter
```

**Comment by james777b** [comment]
I'm having the same issue. Fresh pip install today; re-installed. I tried all sorts of ways to import converter.

**Comment by pietermarsman** [comment]
This is an issue with your PYTHONPATH. The [converter.py](https://github.com/pdfminer/pdfminer.six/blob/master/pdfminer/converter.py) is just there. Either remove conflicting installs from other versions of pdfminer, or make sure that pdfminer itself is on your PYTHONPATH.
