### ISSUE TITLE
Unhandled BrokenPipeError in pdf2txt or dumppdf

### ISSUE THREAD

**Issue by musicinmybrain** [pdfminer/pdfminer.six#875]
**Bug report**

When the output of `pdf2txt` or `dumppdf` is directed to a pipe, but the pipe reader closes the pipe before the command has written the complete output (for example, because the pipe reader is the `head` command), an unhandled `BrokenPipeError` is presented to the user.

```
$ pdf2txt ./samples/nonfree/i1040nr.pdf | head >/dev/null
Traceback (most recent call last):
  File "/usr/bin/pdf2txt", line 317, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/bin/pdf2txt", line 311, in main
    outfp = extract_text(**vars(parsed_args))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/pdf2txt", line 62, in extract_text
    pdfminer.high_level.extract_text_to_fp(fp, **locals())
  File "/usr/lib/python3.11/site-packages/pdfminer/high_level.py", line 132, in extract_text_to_fp
    interpreter.process_page(page)
  File "/usr/lib/python3.11/site-packages/pdfminer/pdfinterp.py", line 998, in process_page
    self.device.end_page(page)
  File "/usr/lib/python3.11/site-packages/pdfminer/converter.py", line 81, in end_page
    self.receive_layout(self.cur_item)
  File "/usr/lib/python3.11/site-packages/pdfminer/converter.py", line 332, in receive_layout
    render(ltpage)
  File "/usr/lib/python3.11/site-packages/pdfminer/converter.py", line 321, in render
    render(child)
  File "/usr/lib/python3.11/site-packages/pdfminer/converter.py", line 321, in render
    render(child)
  File "/usr/lib/python3.11/site-packages/pdfminer/converter.py", line 321, in render
    render(child)
  File "/usr/lib/python3.11/site-packages/pdfminer/converter.py", line 323, in render
    self.write_text(item.get_text())
  File "/usr/lib/python3.11/site-packages/pdfminer/converter.py", line 315, in write_text
    cast(TextIO, self.outfp).write(text)
BrokenPipeError: [Errno 32] Broken pipe
```

```
$ dumppdf -a ./samples/nonfree/i1040nr.pdf | head >/dev/null
Traceback (most recent call last):
  File "/usr/bin/dumppdf", line 473, in <module>
    main()
  File "/usr/bin/dumppdf", line 457, in main
    dumppdf(
  File "/usr/bin/dumppdf", line 280, in dumppdf
    dumpallobjs(outfp, doc, codec, show_fallback_xref)
  File "/usr/bin/dumppdf", line 135, in dumpallobjs
    dumpxml(out, obj, codec=codec)
  File "/usr/bin/dumppdf", line 45, in dumpxml
    out.write("</dict>")
BrokenPipeError: [Errno 32] Broken pipe
```

It seems like this should probably be handled and converted into a graceful exit.

Downstream bug report: https://bugzilla.redhat.com/show_bug.cgi?id=2186554

**Comment by azellner86** [comment]
came across the same issue a few days ago and proposed a fix
