### ISSUE TITLE
setup.py Python 2.6 failure

### ISSUE THREAD

**Issue by metachris** [pdfminer/pdfminer.six#9]
```
Downloading pdfminer.six-20151013.zip (4.2MB)
  100% |################################| 4.2MB 141kB/s 
  Traceback (most recent call last):
    File "<string>", line 20, in <module>
    File "/tmp/pip-build-QgQ8RT/pdfminer.six/setup.py", line 12, in <module>
      install_requires=['six', 'chardet'] if sys.version_info.major>2 else ['six'],
  AttributeError: 'tuple' object has no attribute 'major'
  Complete output from command python setup.py egg_info:
  Traceback (most recent call last):

    File "<string>", line 20, in <module>

    File "/tmp/pip-build-QgQ8RT/pdfminer.six/setup.py", line 12, in <module>

      install_requires=['six', 'chardet'] if sys.version_info.major>2 else ['six'],

  AttributeError: 'tuple' object has no attribute 'major'
```

**Comment by eracle** [comment]
Please, use [pdfminer](https://github.com/euske/pdfminer) instead.
