### ISSUE TITLE
Error when dump all

### ISSUE THREAD

**Issue by BrunIF** [pdfminer/pdfminer.six#94]
When I run this command with this file

dumppdf -a [invalid.pdf](https://github.com/pdfminer/pdfminer.six/files/1333587/invalid.pdf)

receive error message: 
```
$ dumppdf -a invalid.pdf 
<pdf>Traceback (most recent call last):
  File "/usr/bin/dumppdf", line 268, in <module>
    if __name__ == '__main__': sys.exit(main(sys.argv))
  File "/usr/bin/dumppdf", line 265, in main
    dumpall=dumpall, codec=codec, extractdir=extractdir)
  File "/usr/bin/dumppdf", line 216, in dumppdf
    dumpallobjs(outfp, doc, codec=codec)
  File "/usr/bin/dumppdf", line 102, in dumpallobjs
    obj = doc.getobj(objid)
  File "/usr/local/lib/python2.7/dist-packages/pdfminer/pdfdocument.py", line 658, in getobj
    assert objid != 0
AssertionError
```

**Comment by abhishek-27** [comment]
Did you get any solution for this? Even I am facing the same issue.

**Comment by BrunIF** [comment]
No. Sometimes some PDF files I get this error.

**Comment by abhishek-27** [comment]
Yea same here. Even I am getting the same error for only a few pdfs.
