### ISSUE TITLE
ImportError: cannot import name 'PDFObjectNotFound'

### ISSUE THREAD

**Issue by dekken201** [pdfminer/pdfminer.six#95]
Hello! I'm using this module on python3 to extract data from few PDFs, and it was working flawlessly a couple weeks ago. Now, whenever I try to use the exact same code, with the same library that wasn't updated at all, I keep getting this error:

`Traceback (most recent call last):
  File "getTxt.py", line 5, in <module>
    from pdfminer.pdfpage import PDFPage
  File "C:\Users\Luke\Anaconda3\lib\site-packages\pdfminer\pdfpage.py", line 4, in <module>
    from .pdftypes import PDFObjectNotFound
ImportError: cannot import name 'PDFObjectNotFound'`

I thought it could be something about it not finding the pdf, but I even put it inside the folder with the code and it keeps giving me the same error.

**Comment by AlternNO** [comment]
> 
> 
> Well, I'll just answer it myself, I think I found the solution.
> I updated pdfminer.six and it stood the same.
> So I searched the internet and found a post saying to change from "from cStringIO import StringIO"
> to "from io import StringIO" and it worked.
> Anyways, I'll be closing this, thanks for reading :P

Could you please tell me where in the code you did the changes? In one of the files in 
\Anaconda3\Lib\site-packages\pdfminer\
or in the code you were working in?

**Comment by dekken201** [comment]
@AlternNO hey man, I just changed my import method, in my code, didn't mess with pdfminer itself.

**Comment by mdrijwan123** [comment]
Just install pdfminer.six for python 3.7 and remove pdfminer3k if installed. This solved my case
